learning-process/ppc-2025-threads

tasks/stl/krylov_m_monte_carlo/func_tests/main.cpp
tasks/stl/krylov_m_monte_carlo/include/mci_common.hpp
tasks/stl/krylov_m_monte_carlo/include/mci_seq.hpp
tasks/stl/krylov_m_monte_carlo/include/mci_stl.hpp
tasks/stl/krylov_m_monte_carlo/perf_tests/main.cpp
tasks/stl/krylov_m_monte_carlo/src/mci_common.cpp
tasks/stl/krylov_m_monte_carlo/src/mci_seq.cpp
tasks/stl/krylov_m_monte_carlo/src/mci_stl.cpp

На вход подается функция для интегрирования, принимающая координату точки в виде вектора значений, вектор пределов интегрирования, определяющий размерность функции, и точность, определяемую числом итераций.
На каждой итерации производится выбор случайной точки в заданной области, значения функции в точках суммируются. После выполнения всех итераций, итоговая оценка интеграла вычисляется как среднее значение функции, умноженное на объем области интегрирования - произведение длин ее сторон в каждой плоскости.
Распараллеливание происходит на уровне цикла по числу итераций.
Буфер координат точки инициализируется отдельно для каждого потока, поскольку не может быть разделяемым по определению. Генератор случайных чисел `mt19937` разделяем, но из-за реализованной им синхронизации разделенный …

Крылов Михаил. Вариант 12. Технология STL. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/all/krylov_m_monte_carlo/func_tests/main.cpp
tasks/all/krylov_m_monte_carlo/include/mci_all.hpp
tasks/all/krylov_m_monte_carlo/include/mci_common.hpp
tasks/all/krylov_m_monte_carlo/include/mci_seq.hpp
tasks/all/krylov_m_monte_carlo/perf_tests/main.cpp
tasks/all/krylov_m_monte_carlo/src/mci_all.cpp
tasks/all/krylov_m_monte_carlo/src/mci_common.cpp
tasks/all/krylov_m_monte_carlo/src/mci_seq.cpp

На вход подается функция для интегрирования, принимающая координату точки в виде вектора значений, вектор пределов интегрирования, определяющий размерность функции, и точность, определяемую числом итераций.
На каждой итерации производится выбор случайной точки в заданной области, значения функции в точках суммируются. После выполнения всех итераций, итоговая оценка интеграла вычисляется как среднее значение функции, умноженное на объем области интегрирования - произведение длин ее сторон в каждой плоскости.
Распараллеливание на обоих уровнях происходит на уровне цикла по числу итераций.
Буфер координат точки инициализируется отдельно для каждого потока, поскольку не может быть разделяемым по определению. Генератор случайных чисел `mt19937` разделяем, но из-за реализованной им …

Крылов Михаил. Вариант 12. Технологии MPI+STL. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/seq/kovalev_k_radix_sort_batcher_merge/func_tests/main_func.cpp
tasks/seq/kovalev_k_radix_sort_batcher_merge/include/header.hpp
tasks/seq/kovalev_k_radix_sort_batcher_merge/perf_tests/main_perf.cpp
tasks/seq/kovalev_k_radix_sort_batcher_merge/src/sourse.cpp

Задача состоит в реализации поразрядной сортировки массива целых чисел (последовательная реализация, сортировка в порядке возрастания). 
Метод Сountbyte подсчитывает количество байтов в заданном представлении каждого элемента массива mas. Результаты записываются в массив count, где count[i] содержит количество байт со значением i в массиве.
Метод RadixUnsigned использует countbyte для сортировки массива беззнаковых целых чисел. Проходит по каждому байту числа и сортирует элементы по этому байту, используя накопительные подсчеты. Временная память mas_tmp используется для хранения отсортированных элементов на каждом этапе.
Метод RunImpl вызывает RadixUnsigned для исходного массива, приведённого к беззнаковому типу. Т.к. в двоичной записи отрицательного целого числа знак записывается в …

Ковалев Константин. Вариант 18. Технология SEQ. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера..

---

tasks/seq/khasanyanov_k_trapezoid_method/func_tests/main.cpp
tasks/seq/khasanyanov_k_trapezoid_method/include/integrate_seq.hpp
tasks/seq/khasanyanov_k_trapezoid_method/include/integrator.hpp
tasks/seq/khasanyanov_k_trapezoid_method/perf_tests/main.cpp
tasks/seq/khasanyanov_k_trapezoid_method/src/integrate_seq.cpp
tasks/seq/khasanyanov_k_trapezoid_method/src/integrator.cpp

Для вычисления многомерных интегралов используется метод трапеций, который заменяет интеграл конечной суммой по каждой из осей интегрирования. Интеграл вычисляется до получения заданной точности путём увеличения количества частей, на которые делится отрезок интегрирования. Так же для каждой точки вычисляется её вклад в результат путём вычисления веса заданной точки по определённой оси.

Хасаньянов Кирилл. Задача 1. Вариант 10. Технология SEQ. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).

---

tasks/all/krylov_m_monte_carlo/func_tests/main.cpp
tasks/all/krylov_m_monte_carlo/perf_tests/main.cpp
tasks/omp/krylov_m_monte_carlo/func_tests/main.cpp
tasks/omp/krylov_m_monte_carlo/perf_tests/main.cpp
tasks/seq/krylov_m_monte_carlo/func_tests/main.cpp
tasks/seq/krylov_m_monte_carlo/perf_tests/main.cpp
tasks/stl/krylov_m_monte_carlo/func_tests/main.cpp
tasks/stl/krylov_m_monte_carlo/perf_tests/main.cpp
tasks/tbb/krylov_m_monte_carlo/func_tests/main.cpp
tasks/tbb/krylov_m_monte_carlo/perf_tests/main.cpp

Падения происходят практически независимо от числа потоков из-за случайной природы метода Монте-Карло.
Сходимость некоторых подобранных функций - в частности, двух, у которых интеграл с заданными пределами приблизительно равен нулю - оказалась не совсем хорошей. Для других случаев рассматривалась и рассматривается относительная погрешность, а для этих допустимая абсолютная погрешность была увеличена, как и число итераций для повышения точности.
В тесты на производительность добавлена верификация результата.
Относится ко всем пяти задачам.

fix: Крылов Михаил. Вариант 12. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/seq/borisov_s_strassen_seq/func_tests/main.cpp
tasks/seq/borisov_s_strassen_seq/include/ops_seq.hpp
tasks/seq/borisov_s_strassen_seq/perf_tests/main.cpp
tasks/seq/borisov_s_strassen_seq/src/ops_seq.cpp

Реализован алгоритм Штрассена для умножения плотных матриц (элементы типа double). Если матрицы прямоугольные или размерность не является степенью двойки, я дополняю их нулями до ближайшей степени двойки. При малом размере (n <= 16) используется обычное умножение (O(n^3)), а для больших задействуется рекурсивный Штрассена с асимптотикой примерно O(n^(2.8074)), что быстрее, чем классический O(n^3). Такой подход корректно обрабатывает любые размеры (включая прямоугольные) и обеспечивает выигрыш по скорости на крупных матрицах.

Борисов Сергей. Задача 1. Вариант 3. Технология SEQ. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

---

scripts/create_perf_table.py
tasks/seq/shulpin_i_Jarvis_passage/func_tests/main.cpp
tasks/seq/shulpin_i_Jarvis_passage/include/ops_seq.hpp
tasks/seq/shulpin_i_Jarvis_passage/perf_tests/main.cpp
tasks/seq/shulpin_i_Jarvis_passage/src/ops_seq.cpp

-  Определяем количество точек (total).
-  Очищаем output_jar, куда будем записывать результат.
2. Поиск начальной точки:
-  Ищем самую левую нижнюю точку (минимальная x, а если x одинаковые, то минимальная y).
-  Сохраняем её индекс в start и начинаем алгоритм с этой точки (active = start).
3. Основной цикл построения оболочки:
-  Добавляем текущую точку (active) в output_jar и помечаем её как использованную.
-  Выбираем первого кандидата (candidate), следующего по индексу.
-  Перебираем все остальные точки (index) и ищем наиболее левую относительно текущей (active).
-  Для этого используем функцию orientation(), которая проверяет, образуют ли три точки левый поворот.
-  - Если orientation(active, index, candidate) == 2, обновляем candidate.
- …

Шульпин Илья. Вариант 23. Технология SEQ. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/seq/ermilova_d_shell_sort_batcher_even-odd_merger/func_tests/main.cpp
tasks/seq/ermilova_d_shell_sort_batcher_even-odd_merger/include/ops_seq.hpp
tasks/seq/ermilova_d_shell_sort_batcher_even-odd_merger/perf_tests/main.cpp
tasks/seq/ermilova_d_shell_sort_batcher_even-odd_merger/src/ops_seq.cpp

Последовательная сортировка.
-Генерация последовательности шагов (gaps) — используется последовательность Седжвика.
-Сортировка Шелла с убывающим шагом — сначала элементы сравниваются и переставляются на больших расстояниях, завершение при шаге 1 — на последнем этапе выполняется обычная сортировка вставками.
Использование последовательности Седжвика снижает сложность сортировки.

Ермилова Дарья. Задача 1. Вариант 16. Технология SEQ. Сортировка Шелла с четно-нечетным слиянием Бэтчера.

---

tasks/seq/kudryashova_i_radix_batcher/func_tests/kudryashovaRadixBatcherFuncSeq.cpp
tasks/seq/kudryashova_i_radix_batcher/include/kudryashovaRadixBatcherSeq.hpp
tasks/seq/kudryashova_i_radix_batcher/perf_tests/kudryashovaRadixBatcherPerfSeq.cpp
tasks/seq/kudryashova_i_radix_batcher/src/kudryashovaRadixBatcherSeq.cpp

Так как слияние Бэтчера используется в основном в параллельных вычислениях, то в seq версии мною был реализован лишь алгоритм поразрядной сортировки. 
Функция radix_double_sort сортирует массив чисел типа double, используя алгоритм поразрядной сортировки. Сначала создаём вектор converted для хранения представлений double в формате uint64_t. Каждое число преобразуется в uint64_t, при этом обрабатывается знак: если старший бит равен 1, число инвертируется, иначе инвертируется только старший бит. После этого функция выполняет сортировку поразрядно, проходя через каждый байт числа от младшего к старшему. В каждом проходе создаём массив подсчета, который фиксирует количество вхождений каждого байта. 
Далее получим массив префиксных сумм, который позволяет определить, куда именно нужно …

Кудряшова Ирина. Вариант 20. Технология SEQ. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера

---

tasks/omp/lopatin_i_monte_carlo/func_tests/lopatinMonteCarloFuncOMP.cpp
tasks/omp/lopatin_i_monte_carlo/include/lopatinMonteCarloOMP.hpp
tasks/omp/lopatin_i_monte_carlo/perf_tests/lopatinMonteCarloPerfOMP.cpp
tasks/omp/lopatin_i_monte_carlo/src/lopatinMonteCarloOMP.cpp

This task implements a **parallel version** of Monte Carlo integration using OpenMP. The algorithm computes multi-dimensional integrals through parallel random sampling. Key enhancements over sequential version:
- Parallel point generation and function evaluation
- Thread-safe random number generation
- Reduced computation time through workload distribution
Read integration bounds (min/max pairs for each dimension)
Store the number of iterations for sampling
Verify output buffer exists and can store 1 value
Ensure inputs contain:
Even number of bounds (pairs of min/max)
Single integer for iteration count
Initializing random generator that depends on system time, creating a vector for seeds for each thread.
Calculate integration region volume:
$V = \prod(max_i - min_i)$ for all dimensions …

Лопатин Илья. Вариант 12. Технология OMP. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/seq/kozlova_e_contrast_enhancement/func_tests/main.cpp
tasks/seq/kozlova_e_contrast_enhancement/include/ops_seq.hpp
tasks/seq/kozlova_e_contrast_enhancement/perf_tests/main.cpp
tasks/seq/kozlova_e_contrast_enhancement/src/ops_seq.cpp

Полутоновое изображение представлено вектором целых чисел. Значения пикселей изображения масштабируются на весь диапазон от 0 до 255. Для этого находятся минимальное и максимальное значения пикселей, которые используются как конечные точки для растяжки, распределяя все пиксели между этими границами.

Козлова Екатерина. Вариант 28. SEQ. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы.

---

tasks/omp/korovin_n_qsort_batcher_omp/func_tests/main.cpp
tasks/omp/korovin_n_qsort_batcher_omp/include/ops_omp.hpp
tasks/omp/korovin_n_qsort_batcher_omp/perf_tests/main.cpp
tasks/omp/korovin_n_qsort_batcher_omp/src/ops_omp.cpp

Данный код реализует сортировку Хоара с четно-нечетным слиянием Бэтчера. Основная идея состоит в том, чтобы:
- Разбить исходный массив на независимые блоки
- Локально отсортировать каждый блок с помощью рекурсивной QuickSort с параллелизмом на ранних этапах рекурсии
- Объединить отсортированные блоки в единый массив через итеративное четно-нечетное слияние, выполняемое параллельно
---
- **Выбор опорного элемента**  
- **Разбиение массива**  
- **Параллелизация рекурсии:**  
- Определяется максимальная глубина параллельных вызовов как `max_depth = log2(omp_get_num_threads()) + 1`
- Если текущая глубина меньше `max_depth`, рекурсивные вызовы для левой и правой частей запускаются параллельно с использованием директивы `#pragma omp parallel sections`
- При достижении порога глубины рекурсия …

Коровин Никита. Вариант 14. Технология OMP. Сортировка Хоара с четно-нечетным слиянием Бэтчера.

---

tasks/seq/kovalchuk_a_shell_sort/func_tests/main.cpp
tasks/seq/kovalchuk_a_shell_sort/include/ops_seq.hpp
tasks/seq/kovalchuk_a_shell_sort/perf_tests/main.cpp
tasks/seq/kovalchuk_a_shell_sort/src/ops_seq.cpp

Последовательная версия Сортировки Шелла: Итеративно уменьшаем gap начиная с n/2  Для каждого gap элементы сравниваются и сдвигаются на gap, на последней итерации gap = 1

Ковальчук Александр. Вариант 15. Технология SEQ. Сортировка Шелла с простым слиянием

---

tasks/seq/kolokolova_d_integral_simpson_method_seq/perf_tests/main.cpp

Благодаря ревью в https://github.com/learning-process/ppc-2025-threads/pull/266 было замечено, что в seq версии также слишком быстро проходят тесты, так что размер входных данных был немного увеличен

Fix perf Колоколова Дарья. Вариант 11. Технология SEQ. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

---

tasks/omp/gusev_n_sorting_int_simple_merging/func_tests/main.cpp
tasks/omp/gusev_n_sorting_int_simple_merging/include/ops_omp.hpp
tasks/omp/gusev_n_sorting_int_simple_merging/perf_tests/main.cpp
tasks/omp/gusev_n_sorting_int_simple_merging/src/ops_omp.cpp
tasks/omp/gusev_n_sorting_int_simple_merging/src/ops_seq.cpp

Входной массив разделяется на два: для отрицательных и положительных чисел.
Используется #pragma omp parallel для параллельного выполнения этого шага. Каждый поток создает локальные векторы (local_neg, local_pos), которые затем объединяются в общие векторы (negatives, positives) с помощью #pragma omp critical
Для каждого разряда (единицы, десятки, сотни и т.д.) выполняется сортировка подсчетом (в CountingSort).
CountingSort: используется #pragma omp parallel для параллельного подсчета цифр в каждом разряде. Локальные счетчики (local_count) объединяются в общий массив count с помощью #pragma omp critical
Используется #pragma omp parallel sections для параллельной сортировки отрицательных и положительных чисел. После сортировки результаты объединяются в исходный массив

Гусев Никита. Вариант 17. Технология OMP. Поразрядная сортировка для целых чисел с простым слиянием

---

tasks/omp/kudryashova_i_radix_batcher/func_tests/kudryashovaRadixBatcherFuncOMP.cpp
tasks/omp/kudryashova_i_radix_batcher/include/kudryashovaRadixBatcherOMP.hpp
tasks/omp/kudryashova_i_radix_batcher/perf_tests/kudryashovaRadixBatcherPerfOMP.cpp
tasks/omp/kudryashova_i_radix_batcher/src/kudryashovaRadixBatcherOMP.cpp

Данная реализация демонстрирует поразрядную сортировку и чётно-нечётное слияние Бэтчера с использованием технологии OpenMP для параллелизации.
_RunImpl()_ организует процесс сортировки входных данных, разбивая их на блоки для параллельной обработки Сначала происходит параллельная сортировка блоков массива с использованием _RadixDoubleSort_. Затем, в цикле, происходит итеративное слияние отсортированных блоков с использованием _BatcherMerge_, где размер сливаемых блоков увеличивается вдвое на каждом шаге.
Функция _RadixDoubleSort_ сортирует массив чисел типа double, используя алгоритм поразрядной сортировки Каждое число преобразуется в uint64_t, при этом обрабатывается знак. После этого функция выполняет сортировку поразрядно, проходя через каждый байт числа от младшего к старшему. В …

Кудряшова Ирина. Вариант 20. Технология OMP. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера

---

tasks/omp/sozonov_i_image_filtering_block_partitioning/func_tests/main.cpp
tasks/omp/sozonov_i_image_filtering_block_partitioning/include/ops_omp.hpp
tasks/omp/sozonov_i_image_filtering_block_partitioning/perf_tests/main.cpp
tasks/omp/sozonov_i_image_filtering_block_partitioning/src/ops_omp.cpp

**Стандартная свертка Гаусса (3×3):**
Ядро Гаусса 3x3 (нормированное) для σ=1 имеет вид: 
Каждому пикселю изображения ставится в соответствие новая величина, полученная как сумма произведений значений пикселей из окрестности 3×3 на коэффициенты ядра Гаусса.
Например, если центральный пиксель изображения **𝐼(𝑥, 𝑦)**, то его новое значение **𝐼′(𝑥, 𝑦)** будет: 
**Параллельная реализация:**
Для ускорения вычислений разбиваем изображение на блоки и обрабатываем их параллельно, используя OpenMP.
**1. Разбиение на блоки**
- Определяем размер блоков `block_size`.
- Двигаемся по изображению, обрабатывая его кусочками, а не по всей ширине/высоте сразу.
**2. Параллельная обработка**
- Используем `#pragma omp parallel for schedule(dynamic, 1)`, чтобы каждый поток обрабатывал по одной строке блоков.
- …

Созонов Илья. Вариант 26. Технология OMP. Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3.

---

tasks/omp/khovansky_d_double_radix_batcher/func_tests/main.cpp
tasks/omp/khovansky_d_double_radix_batcher/include/ops_omp.hpp
tasks/omp/khovansky_d_double_radix_batcher/perf_tests/main.cpp
tasks/omp/khovansky_d_double_radix_batcher/src/ops_omp.cpp

Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.
1. Validation
Проверяется наличие входного и выходного массивов.
Убеждается, что массивы имеют одинаковый размер.
Если данные некорректны, выполнение завершается.
2. Preprocessing
Входной массив копируется во внутреннюю структуру данных, чтобы избежать модификации исходных данных.
3. Run
Преобразование чисел:
Числа типа double конвертируются в 64-битное представление (uint64_t), что позволяет корректно работать с их битовой структурой.
Поразрядная сортировка:
Выполняется сортировка по битам с использованием разбиения на 256 бакетов (значения байтов).
Частоты значений рассчитываются параллельно с помощью OpenMP.
Выполняется перестановка элементов на основе накопленных частот.
Сортировка …

Хованский Дмитрий. Вариант 20. Технология OMP. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

---

tasks/omp/gromov_a_fox_algorithm/func_tests/main.cpp
tasks/omp/gromov_a_fox_algorithm/include/ops_omp.hpp
tasks/omp/gromov_a_fox_algorithm/perf_tests/main.cpp
tasks/omp/gromov_a_fox_algorithm/src/ops_omp.cpp

`PreProcessingImpl()`
- Делит входные данные на две матрицы `𝐴` и `𝐵`
- Определяет размер матрицы 𝑛 и размер блока `block_size_`
- Проверяет, что матрица квадратная
`ValidationImpl():`
- Проверяет корректность входных данных: размеры должны быть чётными (две матрицы), сама матрица — квадратной
`RunImpl():`
- Делит матрицы на блоки размером `block_size_`
- Выполняет блочное умножение в несколько стадий с использованием OpenMP
- Использует три вычислительных цикла для обработки блоков: Внешний цикл по `i` параллелизуется через `#pragma omp parallel for default(none)`. Внутренние циклы по `bi`, `bj`, `bk` выполняются последовательно внутри каждого потока
`PostProcessingImpl():`
- Копирует результат из `output_` в выходной буфер

Громов Алексей. Вариант 2. Технология OMP. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

---

scripts/generate_perf_results.sh

Fail when `run_tests.py` script execution fails

Enable 'pipefail' in scripts/generate_perf_results.sh

---

.github/workflows/main.yml

- Add missing process level parallelism enforcement for task 'all'
- Set `PROC_COUNT` and `OMP_NUM_THREADS` for the correct step

[CI] Fix perf tests run

---

tasks/omp/kapustin_i_jarv_alg/func_tests/main.cpp
tasks/omp/kapustin_i_jarv_alg/include/ops_omp.hpp
tasks/omp/kapustin_i_jarv_alg/perf_tests/main.cpp
tasks/omp/kapustin_i_jarv_alg/src/ops_omp.cpp

Основные этапы работы:
1)Предварительная обработка (PreProcessing):
-Загружает входные точки из task_data.
-Находит самую левую точку (стартовую точку для алгоритма).
2)Параллельный поиск выпуклой оболочки (RunImpl):
-Использует идею алгоритма Джарвиса: на каждом шаге выбирается точка, которая образует наименьший угол с текущей точкой.
-OpenMP (#pragma omp parallel) распараллеливает перебор точек, ускоряя поиск следующей точки оболочки.
-В критической секции (#pragma omp critical) корректируется глобально лучший кандидат на следующую точку.
-Процесс повторяется, пока алгоритм не вернётся в начальную точку, замыкая оболочку.
3)Постобработка (PostProcessing):
-Копирует полученную выпуклую оболочку в выходные данные task_data.

Капустин Иван. Вариант 23. Технология OMP. Построение выпуклой оболочки - проход Джарвиса.

---

tasks/tbb/muhina_m_dijkstra/func_tests/main.cpp
tasks/tbb/muhina_m_dijkstra/include/ops_tbb.hpp
tasks/tbb/muhina_m_dijkstra/perf_tests/main.cpp
tasks/tbb/muhina_m_dijkstra/src/ops_tbb.cpp

1.  **`PreProcessingImpl()`**:
*   Граф представлен в виде последовательности целых чисел, где `kEndOfVertexList` обозначает конец списка соседей для каждой вершины.
*   Инициализируется вектор `distances_` значением `INT_MAX` для всех вершин.
*   Определяется начальная вершина `start_vertex_` из `task_data->inputs[1]`  или используется вершина 0 по умолчанию.
*   Устанавливается расстояние до `start_vertex_` равным 0.
2.  **`RunImpl()`**:
*   **Построение списка смежности (`adj_list`)**:  Обрабатываются входные данные графа и строится список смежности (`std::vector<std::vector<std::pair<size_t, int>>>`) для представления графа. Каждая запись в списке содержит целевую вершину и вес ребра.
*   **Инициализация приоритетной очереди (`pq`)**: Создается `oneapi::tbb::concurrent_priority_queue` …

Мухина Маргарита. Вариант 21. Технология TBB. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры)

---

tasks/omp/tsatsyn_a_radix_sort_simple_merge/perf_tests/main.cpp
tasks/seq/tsatsyn_a_radix_sort_simple_merge/perf_tests/main.cpp

perf_tests приведены к одному размеру входных данных и к одинаковым границам рандомно генерируемых элементов
https://github.com/learning-process/ppc-2025-threads/pull/367

FIX Цацын Александр. Вариант 19. Технология SEQ,OMP. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием. 

---

tasks/tbb/korovin_n_qsort_batcher/func_tests/main.cpp
tasks/tbb/korovin_n_qsort_batcher/include/ops_tbb.hpp
tasks/tbb/korovin_n_qsort_batcher/perf_tests/main.cpp
tasks/tbb/korovin_n_qsort_batcher/src/ops_tbb.cpp

Данный код реализует сортировку Хоара с четно-нечетным слиянием Бэтчера. Основная идея состоит в том, чтобы:
- Разбить исходный массив на независимые блоки
- Локально отсортировать каждый блок с помощью рекурсивной QuickSort с параллелизмом на ранних этапах рекурсии
- Объединить отсортированные блоки в единый массив через итеративное четно-нечетное слияние, выполняемое параллельно
---
- **Выбор опорного элемента**  
- **Разбиение массива**  
- **Параллелизация рекурсии:**  
- Определяется максимальная глубина параллельных вызовов как `max_depth = log2(tbb::this_task_arena::max_concurrency()) + 1`
- Если текущая глубина меньше `max_depth`, рекурсивные вызовы для левой и правой частей запускаются параллельно с использованием `tbb::task_group::run`
- При достижении порога глубины рекурсия …

Коровин Никита. Вариант 14. Технология TBB. Сортировка Хоара с четно-нечетным слиянием Бэтчера.

---

tasks/omp/petrov_a_radix_double_batcher/perf_tests/main.cpp
tasks/seq/petrov_a_radix_double_batcher/perf_tests/main.cpp

Для стабильности результатов замеров производительности перешел в предыдущих задачах на вектор, отсортированный обратно

[fix perf] Петров Артем. Вариант 20. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

---

.github/workflows/main.yml

PPA is not required anymore, since Ubuntu 24.04 is in use. Its repositories already contain gcc-14 package out of the box.

[CI] Remove additional PPA installation on Ubuntu

---

.clang-tidy
tasks/tbb/anufriev_d_integrals_simpson/func_tests/main.cpp
tasks/tbb/anufriev_d_integrals_simpson/include/ops_tbb.hpp
tasks/tbb/anufriev_d_integrals_simpson/perf_tests/main.cpp
tasks/tbb/anufriev_d_integrals_simpson/src/ops_tbb.cpp

Этот Pull Request заменяет последовательную рекурсивную реализацию многомерной интеграции методом Симпсона на оптимизированную версию с использованием Intel Threading Building Blocks (TBB) для повышения производительности на многоядерных системах.
* Замена рекурсии итеративным подходом:
Исходный рекурсивный метод RecursiveSimpsonSum был удален. Рекурсия затрудняет эффективное распараллеливание стандартными конструкциями TBB.
Вместо него реализован итеративный подход, который подготавливает почву для параллельной обработки.
* Параллельное суммирование с tbb::parallel_reduce:
Ядром оптимизации является использование tbb::parallel_reduce. Этот инструмент идеально подходит для параллельного вычисления суммы (или других операций редукции) по большому набору данных.
Он используется для …

Ануфриев Даниил. Задача 1. Вариант 11. Технология TBB. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

---

tasks/seq/khovansky_d_double_radix_batcher/func_tests/main.cpp
tasks/seq/khovansky_d_double_radix_batcher/include/ops_seq.hpp
tasks/seq/khovansky_d_double_radix_batcher/perf_tests/main.cpp
tasks/seq/khovansky_d_double_radix_batcher/src/ops_seq.cpp

Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.
1. Validation: Программа убеждается, что входные и выходные массивы существуют и имеют одинаковый размер. Если данные некорректны, работа прекращается.
2. Preprocessing: Массив сохраняется во внутреннюю структуру, чтобы избежать изменений в исходных данных.
3. Run:
Числа преобразуются в 64-битный формат для удобной работы с их битовым представлением.
Выполняется поразрядная сортировка, которая группирует числа по значениям отдельных битов.
Затем применяется сортировка нечётно-чётным слиянием Бэтчера, которая окончательно упорядочивает массив.
Числа переводятся обратно в double и записываются в выходной массив.
4. Postprocessing: Отсортированные данные из внутренней структуры программы …

Хованский Дмитрий. Вариант 20. Технология SEQ. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

---

tasks/tbb/borisov_s_strassen/func_tests/main.cpp
tasks/tbb/borisov_s_strassen/include/ops_tbb.hpp
tasks/tbb/borisov_s_strassen/perf_tests/main.cpp
tasks/tbb/borisov_s_strassen/src/ops_tbb.cpp

Реализована TBB-версия алгоритма Штрассена для умножения плотных матриц с элементами типа double. Аналогично предыдущей реализации, для прямоугольных матриц или тех, чья размерность не является степенью двойки, матрицы дополняются нулями до ближайшей степени двойки. При малых размерах (n ≤ 64) применяется классическое умножение (O(n^3)), а для больших матриц используется рекурсивный алгоритм Штрассена с асимптотикой O(n^(log₂7) ≈ O(n^2.8074)), что обеспечивает значительный выигрыш по скорости на крупных матрицах.
В TBB-версии параллелизация операций умножения, сложения и вычитания матриц реализована с помощью tbb::parallel_for, при этом для снижения накладных расходов используются tbb::blocked_range с оптимальными grain_size. Для рекурсивной части, где вычисляются семь независимых …

Борисов Сергей. Задача 1. Вариант 3. Технология TBB. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

---

tasks/tbb/kudryashova_i_radix_batcher/func_tests/kudryashovaRadixBatcherFuncTBB.cpp
tasks/tbb/kudryashova_i_radix_batcher/include/kudryashovaRadixBatcherTBB.hpp
tasks/tbb/kudryashova_i_radix_batcher/perf_tests/kudryashovaRadixBatcherPerfTBB.cpp
tasks/tbb/kudryashova_i_radix_batcher/src/kudryashovaRadixBatcherTBB.cpp

Данная реализация демонстрирует поразрядную сортировку и чётно-нечётное слияние Бэтчера с использованием TBB для параллелизации. Функция сортировки RadixDoubleSort работает с числами double, преобразуя их битовое представление в uint64_t для корректной обработки знака и порядка. Основные этапы включают: параллельное преобразование данных в целочисленный формат, поразрядную сортировку по байтам с использованием tbb::combinable для подсчёта частот и обратное преобразование в double. Параллельные циклы tbb::parallel_for ускоряют преобразование данных, подсчёт гистограмм и перераспределение элементов
Слияние Бэтчера реализовано рекурсивно с помощью tbb::parallel_invoke, параллельно сортирует половины массива, а в tbb::parallel_for объединяет отсортированные подмассивы, сравнивая элементы с …

Кудряшова Ирина. Вариант 20. Технология TBB. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера

---

tasks/tbb/ermilova_d_shell_sort_batcher_even_odd_merger/func_tests/main.cpp
tasks/tbb/ermilova_d_shell_sort_batcher_even_odd_merger/include/ops_tbb.hpp
tasks/tbb/ermilova_d_shell_sort_batcher_even_odd_merger/perf_tests/main.cpp
tasks/tbb/ermilova_d_shell_sort_batcher_even_odd_merger/src/ops_tbb.cpp

Задача состоит в том, чтобы частично отсортировать данные, используя сортировку Шелла, а затем используя чётно-нечётное слияние Бэтчера произвести компановку отсортированных данных.
Для сортировки Шелла использовалась последовательность Седжвика, которая даёт среднюю оценку сложности сортировки O(n^7/6), после частино отсортированные данные сливаются в один набор согласно алгоритму чётно-нечётного слияния Бэтчера
**Параллельная схема**:
1. Данные разбиваются на подмассивы между потоками
2. Каждый поток сортирует свой набор данных сортировкой Шелла
3. Отсортированные данные распределяются между потоками
4. Распределённые данные объединяются слиянием Бэтчера

Ермилова Дарья. Задача 3. Вариант 16. Технология TBB. Сортировка Шелла с четно-нечетным слиянием Бэтчера.

---

tasks/tbb/kozlova_e_contrast_enhancement/func_tests/main.cpp
tasks/tbb/kozlova_e_contrast_enhancement/include/ops_tbb.hpp
tasks/tbb/kozlova_e_contrast_enhancement/perf_tests/main.cpp
tasks/tbb/kozlova_e_contrast_enhancement/src/ops_tbb.cpp

Полутоновое изображение представлено вектором целых чисел. Значения пикселей изображения масштабируются на весь диапазон от 0 до 255. Для этого находятся минимальное и максимальное значения пикселей, которые используются как конечные точки для растяжки, распределяя все пиксели между этими границами. Распараллеливание реализовано с использованием Intel TBB через конструкцию tbb::parallel_for внутри task_arena, что позволяет выполнять обработку пикселей параллельно на нескольких потоках, повышая производительность.

Козлова Екатерина. Вариант 28. TBB. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы.

---

tasks/tbb/opolin_d_radix_sort_batcher_merge/func_tests/main.cpp
tasks/tbb/opolin_d_radix_sort_batcher_merge/include/ops_tbb.hpp
tasks/tbb/opolin_d_radix_sort_batcher_merge/perf_tests/main.cpp
tasks/tbb/opolin_d_radix_sort_batcher_merge/src/ops_tbb.cpp

Исходный массив обрабатывается блоками.
Переводим весь массив uint чтобы сортировать и отрицательные и положительные.
Поразрядная сортировка (LSD) для блоков.
Переводим массив с отсортированными блоками обратно в int.
Четно-нечетное слияние Бэтчера:
Рекурсивное разделение:
Массив делится на две части (low-mid и mid-high), которые сливаются параллельно через tbb::parallel_invoke.

Ополин Дмитрий. Вариант 18. Технология TBB. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

---

tasks/omp/opolin_d_radix_sort_betcher_merge/func_tests/main.cpp
tasks/omp/opolin_d_radix_sort_betcher_merge/include/ops_omp.hpp
tasks/omp/opolin_d_radix_sort_betcher_merge/perf_tests/main.cpp
tasks/omp/opolin_d_radix_sort_betcher_merge/src/ops_omp.cpp

1. Делим исходный массив на блоки для параллельной обработки.
2. Применяем алгоритм поразрядной сортировки(LSD) для блоков:
2.1. Создается 10 корзин (от 0 до 9) для распределения элементов по
текущему разряду.
2.2. Переупорядочиваем элементы на основе распределения по корзинам,
сохраняя относительный порядок при равенстве разрядов.
2.3. Для вектора отрицательных чисел порядок элементов реверсируется.
2.4. Вставляем отсортированные блоки в основной массив.
3. Применяем четно-нечетное слияние Бэтчера.
3.1. Слияние участков от start до mid с mid до end, путем сравнения и обмена элементами на расстоянии p(степень 2).

Ополин Дмитрий. Вариант 18. Технология OMP. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

---

tasks/stl/ermilova_d_shell_sort_batcher_even_odd_merger/func_tests/main.cpp
tasks/stl/ermilova_d_shell_sort_batcher_even_odd_merger/include/ops_stl.hpp
tasks/stl/ermilova_d_shell_sort_batcher_even_odd_merger/perf_tests/main.cpp
tasks/stl/ermilova_d_shell_sort_batcher_even_odd_merger/src/ops_stl.cpp

Задача состоит в том, чтобы частично отсортировать данные, используя сортировку Шелла, а затем используя чётно-нечётное слияние Бэтчера произвести компановку отсортированных данных.
Для сортировки Шелла использовалась последовательность Седжвика, которая даёт среднюю оценку сложности сортировки O(n^7/6), после частино отсортированные данные сливаются в один набор согласно алгоритму чётно-нечётного слияния Бэтчера
**Параллельная схема**:
1. Данные разбиваются на подмассивы между потоками
2. Каждый поток сортирует свой набор данных сортировкой Шелла
3. Отсортированные данные распределяются между потоками
4. Распределённые данные объединяются слиянием Бэтчера

Ермилова Дарья. Задача 4. Вариант 16. Технология STL. Сортировка Шелла с четно-нечетным слиянием Бэтчера.

---

tasks/stl/kholin_k_multidimensional_integrals_rectangle/func_tests/main.cpp
tasks/stl/kholin_k_multidimensional_integrals_rectangle/include/ops_stl.hpp
tasks/stl/kholin_k_multidimensional_integrals_rectangle/perf_tests/main.cpp
tasks/stl/kholin_k_multidimensional_integrals_rectangle/src/ops_stl.cpp

**ПОСТАНОВКА ЗАДАЧИ ДЛЯ ОДНОМЕРНОГО ИНТЕГРАЛА**
Необходимо вычислить определённый интеграл на отрезке ([a, b]). Этот
отрезок разбивается на (n) равных частей, где длина каждой части
определяется как
$$ h = \frac{b - a}{n}. $$
b и a - конец и начала отрезка. Вместо b и а подставляются пределы
интегрирования, n - число шагов.
Обозначим через $$f\left(x_{i-1} + \frac{h}{2}\right)$$ значение функции
в середине каждого частичного отрезка. Затем составим сумму произведений
всех таких значений $$f\left(x_{i-1} + \frac{h}{2}\right)$$ на h — шаг
отрезка. Полученная сумма будет представлять собой приближённое значение
определённого интеграла на отрезке ([a, b]) по формуле средних
прямоугольников:
$$ \int_{a}^{b} f(x) , dx \approx h \sum_{i=1}^{n} f\left(x_{i-1} +
\frac{h}{2}\right) = h …

Холин Кирилл. Задача 1. Вариант 9. Технология STL. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников)

---

tasks/stl/borisov_s_strassen/func_tests/main.cpp
tasks/stl/borisov_s_strassen/include/ops_stl.hpp
tasks/stl/borisov_s_strassen/perf_tests/main.cpp
tasks/stl/borisov_s_strassen/src/ops_stl.cpp

Реализована STL-версия алгоритма Штрассена для умножения плотных матриц с элементами типа double. Аналогично другим реализациям, поддерживается работа с прямоугольными матрицами: если размерность не является степенью двойки, исходные матрицы дополняются нулями до ближайшей степени двойки. При малых размерностях (n ≤ 64) используется классическое умножение со сложностью O(n³), тогда как при больших — применяется рекурсивный алгоритм Штрассена со сложностью O(n^log₂7) ≈ O(n^2.8074), что обеспечивает ускорение на крупных входных данных.
В STL-версии параллелизация реализована с использованием std::thread. На каждой рекурсивной итерации алгоритма Штрассена одновременно вычисляются семь независимых подматриц (M1..M7), каждая из которых запускается в отдельном потоке при глубине рекурсии меньше …

Борисов Сергей. Задача 1. Вариант 3. Технология STL. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

---

tasks/stl/sozonov_i_image_filtering_block_partitioning/func_tests/main.cpp
tasks/stl/sozonov_i_image_filtering_block_partitioning/include/ops_stl.hpp
tasks/stl/sozonov_i_image_filtering_block_partitioning/perf_tests/main.cpp
tasks/stl/sozonov_i_image_filtering_block_partitioning/src/ops_stl.cpp

**Стандартная свертка Гаусса (3×3):**
Ядро Гаусса 3x3 (нормированное) для σ=1 имеет вид: 
Каждому пикселю изображения ставится в соответствие новая величина, полученная как сумма произведений значений пикселей из окрестности 3×3 на коэффициенты ядра Гаусса.
Например, если центральный пиксель изображения **𝐼(𝑥, 𝑦)**, то его новое значение **𝐼′(𝑥, 𝑦)** будет: 
**Параллельная реализация:**
Для ускорения вычислений разбиваем изображение на блоки и обрабатываем их параллельно с помощью `std::thread`.
**1. Разбиение на блоки**
-  Устанавливаем размер блока `block_size`.
- Делим изображение на прямоугольные участки (блоки).
- Формируем список координат всех блоков.
**2. Параллельная обработка**
- Запускаем потоки с использованием `std::thread`.
- Каждому потоку динамически назначаются свободные …

Созонов Илья. Вариант 26. Технология STL. Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3.

---

tasks/stl/opolin_d_radix_sort_batcher_merge/func_tests/main.cpp
tasks/stl/opolin_d_radix_sort_batcher_merge/include/ops_stl.hpp
tasks/stl/opolin_d_radix_sort_batcher_merge/perf_tests/main.cpp
tasks/stl/opolin_d_radix_sort_batcher_merge/src/ops_stl.cpp

1. Входной массив int преобразуется в uint32_t для корректной работы с отрицательными числами при поразрядной сортировке.
2. Массив делится на блоки. 
3. Каждый блок сортируется параллельно с использованием стандартной поразрядной сортировки для uint32_t (RadixSortLSD).
4. Массив снова переводится в int.
5. Применяется итеративное четно-нечетное слияние Бэтчера для отсортированных блоков.

Ополин Дмитрий. Вариант 18. Технология STL. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

---

tasks/stl/korneeva_e_sparse_matrix_mult_complex_ccs/func_tests/main.cpp
tasks/stl/korneeva_e_sparse_matrix_mult_complex_ccs/include/ops_stl.hpp
tasks/stl/korneeva_e_sparse_matrix_mult_complex_ccs/perf_tests/main.cpp
tasks/stl/korneeva_e_sparse_matrix_mult_complex_ccs/src/ops_stl.cpp

**Задача:** Умножение двух разреженных матриц с комплексными числами, представленных в формате CCS (Compressed Column Storage). Умножение выполняется с использованием стандартной библиотеки C++ (STL) для параллелизации вычислений с помощью потоков (`std::thread`).
Логика работы:
1. **Разделение работы по столбцам**: Результирующая матрица формируется по столбцам, где каждый столбец вычисляется независимо.
2. **Схема распараллеливания:** Набор столбцов результирующей матрицы распределяется между потоками, количество которых определяется функцией `ppc::util::GetPPCNumThreads()` (на основе переменной окружения `OMP_NUM_THREADS`). Работа делится статически: каждый поток обрабатывает диапазон столбцов, вычисляя ненулевые элементы и их строковые индексы.
3. **Особенности реализации:** Каждый …

Корнеева Екатерина. Вариант 7. Технология STL. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – столбцовый (CCS). 

---

tasks/stl/anufriev_d_integrals_simpson/func_tests/main.cpp
tasks/stl/anufriev_d_integrals_simpson/include/ops_stl.hpp
tasks/stl/anufriev_d_integrals_simpson/perf_tests/main.cpp
tasks/stl/anufriev_d_integrals_simpson/src/ops_stl.cpp

* Параллельное выполнение с std::thread:
Основным механизмом распараллеливания служит std::thread. Это обеспечивает контроль над созданием и управлением потоками, а также широкую совместимость с различными компиляторами и окружениями.
Рекурсивный метод RecursiveSimpsonSum, отвечающий за вычисление интеграла по внутренним измерениям, сохранен и используется каждым потоком для обработки своей части задачи.
* Разделение вычислительной нагрузки:
Интегрирование по первой (внешней) размерности разделяется на подзадачи, каждая из которых назначается отдельному потоку.
Оптимальное количество потоков определяется с помощью std::thread::hardware_concurrency().
Каждый поток независимо вычисляет частичную сумму интеграла, соответствующую его диапазону итераций.
* Обработка многомерной сетки в …

Ануфриев Даниил. Задача 1. Вариант 11. Технология STL. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

---

tasks/stl/bessonov_e_radix_sort_simple_merging/func_tests/main.cpp
tasks/stl/bessonov_e_radix_sort_simple_merging/include/ops_stl.hpp
tasks/stl/bessonov_e_radix_sort_simple_merging/perf_tests/main.cpp
tasks/stl/bessonov_e_radix_sort_simple_merging/src/ops_stl.cpp

1. Параллельная обработка
- Данные разбиваются на блоки по числу потоков (std::thread::hardware_concurrency()).
- Каждый поток работает со своей частью массива при:
- - Конвертации double → uint64_t.
- - Подсчёте частот цифр в каждом разряде.
- - Обратной конвертации uint64_t → double.
3. Поразрядная сортировка (Radix Sort)
- Выполняется 8 проходов (по байту на каждый из 64 бит).
- На каждом проходе:
- - Локально в каждом потоке подсчитываются частоты цифр (0..255).
- - Частоты объединяются в глобальный массив global_count.
- - Вычисляются позиции элементов с помощью std::partial_sum.
- - Элементы переставляются во временный массив temp.

Бессонов Егор. Вариант 19. Технология STL. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.

---

.clang-tidy
tasks/all/lopatin_i_monte_carlo/func_tests/lopatinMonteCarloFuncALL.cpp
tasks/all/lopatin_i_monte_carlo/include/lopatinMonteCarloALL.hpp
tasks/all/lopatin_i_monte_carlo/perf_tests/lopatinMonteCarloPerfALL.cpp
tasks/all/lopatin_i_monte_carlo/src/lopatinMonteCarloALL.cpp

This task implements a parallel version of Monte Carlo integration using a combination of MPI and OpenMP. The algorithm computes multi-dimensional integrals through parallel random sampling across multiple processes and threads. Key enhancements over the OpenMP-only version:
- Distributed computation across multiple MPI processes, enabling scalability to cluster environments
- Parallel point generation and function evaluation within each MPI process using OpenMP
- Efficient data distribution and result aggregation using MPI collective operations
- Improved performance for large-scale computations by leveraging both inter-process and intra-process parallelism
- Root process (rank 0):
Read integration bounds (min/max pairs for each dimension) from the input buffer
Store the number of …

Лопатин Илья. Вариант 12. Технология MPI+OMP. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/all/korovin_n_qsort_batcher/func_tests/func_all.cpp
tasks/all/korovin_n_qsort_batcher/include/ops_all.hpp
tasks/all/korovin_n_qsort_batcher/perf_tests/perf_all.cpp
tasks/all/korovin_n_qsort_batcher/src/ops_all.cpp

Данный код реализует сортировку Хоара с четно-нечетным слиянием Бэтчера. Основная идея состоит в том, чтобы:
- Разбить исходный массив на независимые блоки
- Локально отсортировать каждый блок с помощью рекурсивной QuickSort с параллелизмом на ранних этапах рекурсии
- Объединить отсортированные блоки в единый массив через итеративное четно-нечетное слияние, выполняемое параллельно
---
- **Выбор опорного элемента**  
- **Разбиение массива**  
- **Параллелизация рекурсии:**  
- На начальных этапах рекурсии, когда глубина меньше логарифма числа потоков, сортировка выполняется параллельно с использованием  `#pragma omp parallel sections `
---
- **Разбиение на блоки:**  
Функция `PartitionBlocks` делит исходный массив на `p` блоков с равномерным количеством элементов
- **Итеративное слияние:** …

Коровин Никита. Вариант 14. Технология MPI + OMP. Сортировка Хоара с четно-нечетным слиянием Бэтчера.

---

tasks/all/chernykh_a_multidimensional_integral_rectangle/func_tests/main.cpp
tasks/all/chernykh_a_multidimensional_integral_rectangle/include/ops_all.hpp
tasks/all/chernykh_a_multidimensional_integral_rectangle/perf_tests/main.cpp
tasks/all/chernykh_a_multidimensional_integral_rectangle/src/ops_all.cpp

Задача **вычисления многомерного интеграла методом правых прямоугольников** направлена на численное определение значения интеграла функции нескольких переменных на заданных границах.
- Устанавливаются параметры интегрирования: границы для каждого измерения и количество шагов.
- MPI-процесс с рангом 0 проверяет корректность входных данных: левая граница для каждого измерения должна быть меньше правой, а количество шагов по каждому измерению должно быть положительным.
- Остальным MPI-процессам данные передаются с помощью функции `boost::mpi::broadcast`.
2. **Интегрирование**:
- Вычисляется общее количество точек многомерной сетки.
- Сетка делится на части, и каждая часть обрабатывается отдельным MPI-процессом.
- Внутри каждого MPI-процесса параллельно выполняется …

Черных Андрей. Задача 5. Вариант 9. Технология MPI+OMP. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/all/sarafanov_m_CanonMatMul/func_tests/main.cpp
tasks/all/sarafanov_m_CanonMatMul/include/CanonMatrix.hpp
tasks/all/sarafanov_m_CanonMatMul/include/ops_all.hpp
tasks/all/sarafanov_m_CanonMatMul/perf_tests/main.cpp
tasks/all/sarafanov_m_CanonMatMul/src/CanonMatrix.cpp
tasks/all/sarafanov_m_CanonMatMul/src/ops_all.cpp

Структурные изменения: создана функция CalculateIndexes, определяющая границы итераций для каждого из процессов, также реализована структура IndexesPair, в которой перегружена сериализация. Благодаря этому объекты данной структуры можно передавать с помощью broadcast. 
Распараллеливание с помощью OMP и MPI: разделение итерируемого интервала между потоками происходит с помощью директивы # omp parallel for, что касается использования MPI, распараллеливание происходит в 2 этапа: исходные матрицы распределяются между всеми процессами с помощью broadcast, после чего выполняется необходимое количество умножение элементов и сдвигов матриц. Результаты умножения матриц после сдвигов суммируются в единственную переменную mul_results, которая передается на корневой процесс благодаря gatherv. Так как …

Сарафанов Максим. Вариант 1. Технология MPI + OMP. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона

---

tasks/all/milovankin_m_histogram_stretching/func_tests/main.cpp
tasks/all/milovankin_m_histogram_stretching/include/ops_all.hpp
tasks/all/milovankin_m_histogram_stretching/perf_tests/main.cpp
tasks/all/milovankin_m_histogram_stretching/src/ops_all.cpp

Сначала каждый процесс находит локальные min и max в своей части данных с помощью `parallel_reduce`, затем результаты со всех процессов объединяются через `boost::mpi::all_reduce`. Итоговое изображение получается применением к каждому пикселю формулы `value = ((value - min) * 255 + (max - min)/2) / (max - min)` параллельно в каждом процессе, используя `parallel_for`. Обработанные части изображения собираются на процессе с рангом 0 с помощью `boost::mpi::send/recv`.

Милованкин Максим. Задача 5. Вариант 28. Технология MPI+TBB. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы.

---

tasks/all/smirnov_i_radix_sort_simple_merge/func_tests/main.cpp
tasks/all/smirnov_i_radix_sort_simple_merge/include/ops_all.hpp
tasks/all/smirnov_i_radix_sort_simple_merge/perf_tests/main.cpp
tasks/all/smirnov_i_radix_sort_simple_merge/src/ops_all.cpp

Создаются процессы, которые делят исходный массив на примерно равные части. В них создаются потоки, которые делят исходный массив на примерно равные части выполняют сортировку в функции Sorting. Отсортированные массивы складываются в очередь firstdq. 
Создается новый набор потоков, которые выполняют функцию Merging: из firstdq свободный поток берет первые два отсортированных массива начинает слияние, после чего кладет полученный массив во вторую очередь seconddq. Когда в firstdq не остается массивов, меняются указатели firstdq, seconddq и процесс повторяется, пока не останется один слитый массив в firstdq.
Все данные передаются на нулевой процесс и снова происходит аналогичное слияние.

Смирнов Илья. Вариант 17. Технология MPI+STL. Поразрядная сортировка для целых чисел с простым слиянием.

---

tasks/all/bessonov_e_radix_sort_simple_merging/func_tests/main.cpp
tasks/all/bessonov_e_radix_sort_simple_merging/include/ops_all.hpp
tasks/all/bessonov_e_radix_sort_simple_merging/perf_tests/main.cpp
tasks/all/bessonov_e_radix_sort_simple_merging/src/ops_all.cpp

1. MPI делит массив double чисел между процессами.
2. Каждый процесс сортирует свою часть с помощью поразрядной сортировки (radix sort):
- Значения double преобразуются в uint64_t с учетом порядка байтов.
- Затем сортируются по байтам (8 проходов по 8 бит).
3. Каждая часть снова преобразуется в double.
4. MPI собирает отсортированные куски в rank 0.
5. На rank 0 происходит многопоточное слияние (merge) всех отсортированных блоков.

Бессонов Егор. Вариант 19. Технология MPI+STL. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.

---

tasks/all/borisov_s_strassen/func_tests/main.cpp
tasks/all/borisov_s_strassen/include/ops_all.hpp
tasks/all/borisov_s_strassen/perf_tests/main.cpp
tasks/all/borisov_s_strassen/src/ops_all.cpp
tasks/all/borisov_s_strassen/src/ops_stl.cpp

Параллелизация реализована в два уровня:
1. MPI-уровень
Корневой процесс раскладывает задачу верхнего уровня на семь
независимых произведений P₁…P₇ и распределяет их между
MPI-процессами по формуле owner = Pi % world_size.
Каждый процесс вычисляет только свои Pᵢ и передаёт результат
обратно root-процессу. 
Root-процесс получает все семь Pᵢ, формирует квадранты C₁₁…C₂₂,
собирает итоговую матрицу C.
2. STL-уровень
Внутри каждого MPI-процесса та же рекурсивная функция
StrassenRecursive с использованием std::thread
одновременного вычисления M₁…M₇

Борисов Сергей. Задача 1. Вариант 3. Технология MPI+STL. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

---

tasks/all/shulpin_i_jarvis_passage/func_tests/main.cpp
tasks/all/shulpin_i_jarvis_passage/include/ops_all.hpp
tasks/all/shulpin_i_jarvis_passage/include/test_modules.hpp
tasks/all/shulpin_i_jarvis_passage/perf_tests/main.cpp
tasks/all/shulpin_i_jarvis_passage/src/ops_all.cpp
tasks/all/shulpin_i_jarvis_passage/src/test_modules.cpp

Вспомогательная функция FindLocalCandidate
- Делит весь вектор точек на num_threads равных чанков.
- Каждый поток независимо сканирует свой диапазон, выбирая «лучшего» кандидата на следующий шаг выпуклой оболочки по критерию:
- - поворот против часовой стрелки (cross > 0),
- - при коллинеарности — большая квадратная дистанция до текущей точки.
- Результаты каждого потока записываются в общий массив local_cand, после чего внутри функции снова применяется та же логика сравнения для выбора единственного локального кандидата.
Основная функция MakeJarvisPassageALL
- Инициализация MPI
- - Создаётся и регистрируется пользовательский тип mpi_point для структуры Point.
- - Все ранги получают размер входного массива через MPI_Bcast.
- Поиск стартовой точки
- - Ранг 0 находит …

Шульпин Илья. Вариант 23. Технология MPI + STL. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/all/shvedova_v_graham_convex_hull/src/ops_all.cpp

Добавлено освобождение коммуникатора. Его отсутствие могло вызвать проблему с тестами у других студентов в macos. 
@aobolensk @allnes

[FIX] Шведова Виталина. Вариант 22. Технология MPI+STL. Построение выпуклой оболочки – проход Грэхема.

---

tasks/all/kozlova_e_contrast_enhancement/func_tests/func_all.cpp
tasks/all/kozlova_e_contrast_enhancement/include/ops_all.hpp
tasks/all/kozlova_e_contrast_enhancement/perf_tests/perf_all.cpp
tasks/all/kozlova_e_contrast_enhancement/src/ops_all.cpp

Полутоновое изображение представлено вектором целых чисел. Значения пикселей масштабируются на весь диапазон от 0 до 255. Для этого каждый процесс находит минимум и максимум яркости в своей части данных, после чего используются коллективные операции boost::mpi::all_reduce для вычисления глобальных границ. Передача и сбор данных между процессами выполняются с помощью boost::mpi::broadcast, boost::mpi::scatterv и boost::mpi::gatherv. Повышение контраста выполняется параллельно с использованием директивы #pragma omp parallel for schedule(static).

Козлова Екатерина. Вариант 28. MPI+OMP. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы

---

tasks/all/opolin_d_radix_sort_batcher_merge/func_tests/func_all.cpp
tasks/all/opolin_d_radix_sort_batcher_merge/include/ops_all.hpp
tasks/all/opolin_d_radix_sort_batcher_merge/perf_tests/perf_all.cpp
tasks/all/opolin_d_radix_sort_batcher_merge/src/ops_all.cpp

На главном процессе распределяем данные на все процессы. Каждый процесс локально конвертирует значения в беззнаковые ключи, выполняет многопоточный Radix-sort и обратно переводит в int. Отсортированные участки собираются обратно на главном процессе с помощью gatherv.

Ополин Дмитрий. Вариант 18. Технология MPI+TBB. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

---

tasks/all/kovalchuk_a_shell_sort/func_tests/func_all.cpp
tasks/all/kovalchuk_a_shell_sort/include/ops_all.hpp
tasks/all/kovalchuk_a_shell_sort/perf_tests/perf_all.cpp
tasks/all/kovalchuk_a_shell_sort/src/ops_all.cpp

Root процесс рассылает размер данных всем процессам(total_size)
Разбиваем блоки с помощью scatterv
Каждый процесс сортирует свой блок
С помощью TBB параллелизуем обработку подмассивов в блоке
Собираем на root процессе данные через gatherv
Производим слияние через min-heap

Ковальчук Александр. Вариант 15. Технология MPI + TBB. Сортировка Шелла с простым слиянием

---

tasks/all/kovalev_k_radix_sort_batcher_merge/perf_tests/main_perf.cpp
tasks/omp/kovalev_k_radix_sort_batcher_merge/perf_tests/main_perf.cpp
tasks/seq/kovalev_k_radix_sort_batcher_merge/perf_tests/main_perf.cpp
tasks/stl/kovalev_k_radix_sort_batcher_merge/perf_tests/main_perf.cpp
tasks/tbb/kovalev_k_radix_sort_batcher_merge/perf_tests/main_perf.cpp

Из-за предыдущего исправления (https://github.com/learning-process/ppc-2025-threads/pull/931) размеры perf тестов остались различны в версии seq и прочих, что и исправлено в этом PR

[FIX PERF TESTS] Ковалев Константин. Вариант 18. Технология SEQ. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

---

tasks/all/voroshilov_v_convex_hull_components/include/chc.hpp
tasks/all/voroshilov_v_convex_hull_components/perf_tests/main.cpp
tasks/all/voroshilov_v_convex_hull_components/src/chc.cpp
tasks/all/voroshilov_v_convex_hull_components/src/chc_all.cpp
tasks/omp/voroshilov_v_convex_hull_components/include/chc.hpp
tasks/omp/voroshilov_v_convex_hull_components/perf_tests/main.cpp
tasks/omp/voroshilov_v_convex_hull_components/src/chc.cpp
tasks/seq/voroshilov_v_convex_hull_components/include/chc.hpp
tasks/seq/voroshilov_v_convex_hull_components/perf_tests/main.cpp
tasks/seq/voroshilov_v_convex_hull_components/src/chc.cpp
tasks/stl/voroshilov_v_convex_hull_components/include/chc.hpp
tasks/stl/voroshilov_v_convex_hull_components/perf_tests/main.cpp
tasks/stl/voroshilov_v_convex_hull_components/src/chc.cpp
tasks/tbb/voroshilov_v_convex_hull_components/include/chc.hpp
tasks/tbb/voroshilov_v_convex_hull_components/perf_tests/main.cpp
tasks/tbb/voroshilov_v_convex_hull_components/src/chc.cpp

Внёс оптимизационные изменения во все версии задачи:
1. В `ALL` версии ранее распараллеливание на процессы с помощью `boost::mpi` применялось только во 2-ом этапе задачи (построение оболочек). Теперь поиск компонент тоже параллельный по процессам:
```c++
bool voroshilov_v_convex_hull_components_all::ChcTaskALL::RunImpl() {
std::vector<Component> local_components = FindComponentsMPIOMP(height_in_, width_in_, pixels_in_);
hulls_out_ = QuickHullAllMPIOMP(local_components);
return true;
}
``` 
2. В остальных версиях немного изменены вспомогательные функции:
```c++
void MergeComponentsAcrossAreas(std::vector<Component>& components, Image& image, int area_height,
std::vector<int>& end_y);
template <typename T>
std::vector<T> MergeVectors(std::vector<std::vector<T>>& vectors);
``` 
Оптимизация …

[FIX] Ворошилов Виталий. Вариант 30. Построение выпуклой оболочки для компонент бинарного изображения.
