tasks/seq/sotskov_a_shell_sorting_with_simple_merging/func_tests/main.cpp
tasks/seq/sotskov_a_shell_sorting_with_simple_merging/include/ops_seq.hpp
tasks/seq/sotskov_a_shell_sorting_with_simple_merging/perf_tests/main.cpp
tasks/seq/sotskov_a_shell_sorting_with_simple_merging/src/ops_seq.cpp

Для эффективной сортировки Шелла используется последовательность интервалов. Интервалы на каждом шаге сортировки уменьшаются, что позволяет ускорить алгоритм. Одна из классических последовательностей строится по формуле:
$$
gap = 3 \times gap + 1
$$
Эта формула генерирует интервалы: 1, 4, 13, 40 и так далее. Последовательность строится до тех пор, пока интервал не станет больше размера массива.
Для каждого значения интервала выполняется сортировка элементов, которые находятся на расстоянии этого интервала друг от друга. На каждом шаге интервал уменьшается, и сортировка продолжается до тех пор, пока интервал не станет равным 1.
В данной реализации не используется этап слияния, поэтому отсортированные части массива не объединяются дополнительно — алгоритм завершает работу после стандартной …

Соцков Андрей. Задача 1. Вариант 15. Технология SEQ. Сортировка Шелла с простым слиянием.

---

tasks/tbb/krylov_m_monte_carlo/func_tests/main.cpp
tasks/tbb/krylov_m_monte_carlo/include/mci_common.hpp
tasks/tbb/krylov_m_monte_carlo/include/mci_seq.hpp
tasks/tbb/krylov_m_monte_carlo/include/mci_tbb.hpp
tasks/tbb/krylov_m_monte_carlo/perf_tests/main.cpp
tasks/tbb/krylov_m_monte_carlo/src/mci_common.cpp
tasks/tbb/krylov_m_monte_carlo/src/mci_seq.cpp
tasks/tbb/krylov_m_monte_carlo/src/mci_tbb.cpp

На вход подается функция для интегрирования, принимающая координату точки в виде вектора значений, вектор пределов интегрирования, определяющий размерность функции, и точность, определяемую числом итераций.
На каждой итерации производится выбор случайной точки в заданной области, значения функции в точках суммируются. После выполнения всех итераций, итоговая оценка интеграла вычисляется как среднее значение функции, умноженное на объем области интегрирования - произведение длин ее сторон в каждой плоскости.
Распараллеливание происходит на уровне цикла по числу итераций.
Буфер координат точки инициализируется отдельно для каждого потока, поскольку не может быть разделяемым по определению. Генератор случайных чисел `mt19937` разделяем, но из-за реализованной им синхронизации разделенный …

Крылов Михаил. Вариант 12. Технология TBB. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/seq/kolodkin_g_multiplication_matrix_CRS/func_tests/main.cpp
tasks/seq/kolodkin_g_multiplication_matrix_CRS/include/ops_seq.hpp
tasks/seq/kolodkin_g_multiplication_matrix_CRS/perf_tests/main.cpp
tasks/seq/kolodkin_g_multiplication_matrix_CRS/src/ops_seq.cpp

Описание последовательной задачи:
На вход подается вектор, который содержит данные двух разреженных матриц.
Preproccessing: на этом этапе считывается входной вектор, разделяется на две части(каждый подвектор соответствует данным одной из двух матриц), после чего каждый вектор с помощью функции парсится в структуру SparseMatrixCRS. На выходе получаются две объекта типа SparseMatrixCRS, которые представляют матрицы, которые требуется перемножить.
Validation: проверяется, что количество столбцов первой матрицы равно количеству строк второй матрицы. Если это условие не выполнено, то умножение невозможно.
Run: выполняется умножение матриц. Получившаяся в результате матрица в форме структуры SparseMatrixCRS преобразуется в вектор.
Postprocessing: формируется вектор выходных данных, который …

Колодкин Григорий. Вариант 6. SEQ. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – строковый (CRS).

---

tasks/seq/sorokin_a_multiplication_sparse_matrices_double_ccs/func_tests/main.cpp
tasks/seq/sorokin_a_multiplication_sparse_matrices_double_ccs/include/ops_seq.hpp
tasks/seq/sorokin_a_multiplication_sparse_matrices_double_ccs/perf_tests/main.cpp
tasks/seq/sorokin_a_multiplication_sparse_matrices_double_ccs/src/ops_seq.cpp

Постановка задачи
Задача заключается в реализации последовательного алгоритма умножения разреженных матриц, представленных в формате CCS (Compressed Column Storage). Алгоритм принимает на вход две матрицы в формате CCS и вычисляет их произведение, сохраняя результат также в CCS-формате.
Представление данных:
Матрицы хранятся в разреженном формате CCS, включающем:
values — массив ненулевых элементов.
row_indices — массив индексов строк для ненулевых элементов.
col_ptr — массив указателей на начало каждого столбца.
Входные матрицы:
A размерности M×K.
B размерности K×N.
Выходная матрица 
C размерности M×N сохраняется в том же формате CCS.
Этапы алгоритма:
PreProcessingImpl(): Инициализация входных и выходных данных.
ValidationImpl(): Проверка корректности входных данных.
RunImpl(): Основное …

Сорокин Андрей. Задача 1. Вариант 5. Технология SEQ. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – столбцовый (CCS).

---

tasks/seq/sidorina_p_gradient_method/func_tests/main.cpp
tasks/seq/sidorina_p_gradient_method/include/ops_seq.hpp
tasks/seq/sidorina_p_gradient_method/perf_tests/main.cpp
tasks/seq/sidorina_p_gradient_method/src/ops_seq.cpp

Код реализует метод сопряженных градиентов для решения линейной системы уравнений Ax = b, где A - матрица, x - вектор неизвестных, а b - вектор свободных членов. Важно, что матрица для использования этого метода обязательно должна быть симметрична и положительно определена (условие проверяется в validation).
Начальное приближение решения solution задаётся (обычно нулевым вектором).
residual: разность между правой частью (b) и результатом умножения матрицы на текущее приближение решения.
Цикл итераций:
Вычисляется норма квадрата остатка (residualNormSquared).
Если норма остатка меньше заданной точности (tolerance), то метод завершается, возвращая текущее приближение решения.
В противном случае вычисляется направление поиска (direction), которое является конъюгированным к предыдущим …

Сидорина Полина. Задача 1. Вариант 8. Технология SEQ. Решение систем линейных уравнений методом сопряженных градиентов.

---

tasks/seq/anufriev_d_integrals_simpson/func_tests/main.cpp
tasks/seq/anufriev_d_integrals_simpson/include/ops_seq.hpp
tasks/seq/anufriev_d_integrals_simpson/perf_tests/main.cpp
tasks/seq/anufriev_d_integrals_simpson/src/ops_seq.cpp

Данный документ описывает алгоритм вычисления многомерного интеграла методом Симпсона. Этот метод позволяет аппроксимировать значение интеграла функции многих переменных в заданной области интегрирования.
1.  **Дискретизация области интегрирования:**
*   Задаём область интегрирования как гиперпараллелепипед, определяемый границами по каждой координате: `[a1, b1] x [a2, b2] x ... x [aN, bN]`, где `N` - размерность пространства.
*   Разбиваем каждый отрезок `[ai, bi]` на `ni` равных частей, где `ni` - чётное число. Это создаёт многомерную сетку с узлами, координаты которых определяются по каждой оси `xi = ai + k * hi`, где `k` - индекс узла, а `hi = (bi - ai) / ni` - шаг интегрирования по данной оси.
2.  **Вычисление значений функции в узлах:**
*   Для каждого узла сетки с координатами …

Ануфриев Даниил. Задача 1. Вариант 11. Технология SEQ. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

---

tasks/seq/belov_a_radix_sort_with_batcher_mergesort/func_tests/main.cpp
tasks/seq/belov_a_radix_sort_with_batcher_mergesort/include/ops_seq.hpp
tasks/seq/belov_a_radix_sort_with_batcher_mergesort/perf_tests/main.cpp
tasks/seq/belov_a_radix_sort_with_batcher_mergesort/src/ops_seq.cpp

Разработать последовательную (SEQ) версию алгоритма поразрядной сортировки для целых чисел (Radix sort) с четно-нечетным слиянием Бэтчера. Реализация предназначена для сортировки массивов целых чисел (тип данных bigint выбран как наиболее вместительный и устойчивый к нежелательным переполнениям).
В реализованном алгоритме поразрядной сортировки используется подход LSD (Least Significant Digit), который обрабатывает числа, начиная с младших разрядов. Основным этапом является сортировка чисел по текущему разряду, что выполняется с помощью метода подсчета частоты элементов (Counting Sort). Для обработки чисел с отрицательным значением данные предварительно разделяются на два массива: положительные и отрицательные числа. Отрицательные числа инвертируются, сортируются, а затем их порядок …

Белов Артём. Вариант 18. Технология SEQ. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

---

tasks/seq/shvedova_v_graham_convex_hull/func_tests/main.cpp
tasks/seq/shvedova_v_graham_convex_hull/include/ops_seq.hpp
tasks/seq/shvedova_v_graham_convex_hull/perf_tests/main.cpp
tasks/seq/shvedova_v_graham_convex_hull/src/ops_seq.cpp

Перед выполнением алгоритма производится проверка:
- Количество входных данных кратно 2 (так как передаются координаты точек).
- Число точек больше 2.
- Точки не лежат на одной прямой (проверяется с помощью `CheckCollinearity`).
1. **Поиск опорной точки (pivot)**  
- Выбирается точка с минимальной координатой `y` (если несколько, то с минимальным `x`).
2. **Сортировка точек по углу наклона**
- Используется **угловая сортировка**, где точки упорядочиваются относительно `pivot` по **полярному углу**.
- Дополнительно учитывается расстояние от `pivot`, чтобы отсортировать коллинеарные точки.
3. **Фильтрация точек для выпуклой оболочки**
- Применяется **проход по точкам** с удалением "внутренних" точек (левый поворот или коллинеарность).
- Если следующая точка образует **правый поворот**, то …

Шведова Виталина. Вариант 22. Технология SEQ. Построение выпуклой оболочки – проход Грэхема.

---

tasks/seq/odintsov_m_multmatrix_cannon/func_tests/main.cpp
tasks/seq/odintsov_m_multmatrix_cannon/include/ops_seq.hpp
tasks/seq/odintsov_m_multmatrix_cannon/perf_tests/main.cpp
tasks/seq/odintsov_m_multmatrix_cannon/src/ops_seq.cpp

Описание последовательной версии
0 Определяем размер блока
1 Сдвигаем первоначальные матрица A и B
2 Организуем цикл в котором
2.1 разбиваем матрицы на блоки
2.2 перемножаем блоки и записываем результат в матрицу С
2.3 Сдвигаем блоки
3 Записываем матрицу С в результирующую

Одинцов Михаил. Задача 1. Вариант 1. Технология SEQ. Умножение плотных матриц,типа double,блочная схема, алгоритм Кэннона

---

tasks/seq/oturin_a_gift_wrapping/func_tests/main.cpp
tasks/seq/oturin_a_gift_wrapping/include/ops_seq.hpp
tasks/seq/oturin_a_gift_wrapping/perf_tests/main.cpp
tasks/seq/oturin_a_gift_wrapping/src/ops_seq.cpp

На валидации только отсеиваются случаи, когда количество точек меньше трёх. 
Цель алгоритма - построить такую оболочку, чтобы все точки были либо внутри оболочки, либо были её частью.
Сначала отыскивается самая левая точка (если их несколько на одной координате, то берётся самая высокая). Эта точка добавляется в output_. К этой точке создаётся отрезок с новой точкой, спущенный вертикально вниз относительно первой точки (этот отрезок не будет включён в вывод). Далее ищется наибольший угол этого отрезка и точек из input_. Полученная точка добавляется в output_. Далее начинается цикл до тех пор, пока алгоритм не дойдёт до стартовой точки и не замкнёт оболочку: тоже ищется наибольший угол между двумя последними точками, наилучшая точка добавляется в вывод. 
Ещё, если …

Отурин Александр. Вариант 23. Технология SEQ. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/seq/smirnov_i_radix_sort_simple_merge/func_tests/main.cpp
tasks/seq/smirnov_i_radix_sort_simple_merge/include/ops_seq.hpp
tasks/seq/smirnov_i_radix_sort_simple_merge/perf_tests/main.cpp
tasks/seq/smirnov_i_radix_sort_simple_merge/src/ops_seq.cpp

Алгоритм реализует поразрядную сортировку (Radix Sort) для целочисленного массива, используя цифровую сортировку по разрядам. Сортировка производится от младших разрядов к старшим.
Для каждого разряда используется сортировка подсчётом.
1) Находится максимальный элемент в массиве (longest) и вычисляется количество разрядов (len) в десятичной системе
2) Инициализируется массив counting для хранения частоты цифр (от 0 до 9) и подсчитывается частота цифр для текущего разряда
3) Преобразуется массив counting в массив накопленных частот. Элементы из исходного массива распределяются в новый массив sorting на основе накопленных частот.

Смирнов Илья. Задача 1. Вариант 17. Технология SEQ. Поразрядная сортировка для целых чисел с простым слиянием.

---

tasks/seq/kalyakina_a_Shell_with_simple_merge/func_tests/main.cpp
tasks/seq/kalyakina_a_Shell_with_simple_merge/include/ops_seq.hpp
tasks/seq/kalyakina_a_Shell_with_simple_merge/perf_tests/main.cpp
tasks/seq/kalyakina_a_Shell_with_simple_merge/src/ops_seq.cpp

**Принцип работы алгоритма (сортировка по неубыванию):**
1. **Выбор интервалов:** выбрана последовательность Седжвика (1, 5, 19, 41, 109, 209, ...). Расчет элементов последовательности происходит до момента, когда следующий элемент последовательности, умноженный на 3, будет больше или равен размеру сортируемого массива
2. **Сортировка подмассивов:** сортируются элементы, которые находятся на расстоянии текущего интервала, сортировка происходит вставками.
3. **Уменьшение интервала:** выбираем следующий элемент последовательности Седжвика (в меньшую сторону), пока не дойдем до 1.
Данные шаги выполняются для каждого значения интервала

Калякина Анастасия. Задача 1. Вариант 15. Технология SEQ. Сортировка Шелла с простым слиянием.

---

tasks/seq/chernykh_a_multidimensional_integral_rectangle/func_tests/main.cpp
tasks/seq/chernykh_a_multidimensional_integral_rectangle/include/ops_seq.hpp
tasks/seq/chernykh_a_multidimensional_integral_rectangle/perf_tests/main.cpp
tasks/seq/chernykh_a_multidimensional_integral_rectangle/src/ops_seq.cpp

Задача **вычисления многомерных интегралов методом правых прямоугольников** направлена на численное определение значения интеграла функции нескольких переменных на заданных границах.
- Устанавливаются параметры интегрирования — границы по каждому измерению и количество шагов.
- Проверяется корректность входных данных: границы интегрирования должны быть корректно заданы (левая граница меньше правой), а количество шагов по каждому измерению должно быть положительным.
2. **Интегрирование**:
- Перебираются все точки сетки. Для каждой точки вычисляется значение функции `func_`, представляющей подынтегральную функцию.
3. **Масштабирование результата**:
- Общая сумма значений функции умножается на коэффициент, полученный как произведение размеров шагов по каждому измерению. …

Черных Андрей. Задача 1. Вариант 9. Технология SEQ. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/seq/poroshin_v_multi_integral_with_trapez_method/perf_tests/main.cpp

Мой PR, который на данный момент в мастере, упал из-за превышения времени perf_tests на 0,04 секунды, (https://github.com/learning-process/ppc-2025-threads/pull/62), данный PR решает эту проблему (новый размер разбиений 300->250).

Порошин Владислав. Задача 1. Вариант 10. Технология SEQ. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).

---

tasks/seq/sarafanov_m_CanonMatMul/func_tests/main.cpp
tasks/seq/sarafanov_m_CanonMatMul/include/CanonMatrix.hpp
tasks/seq/sarafanov_m_CanonMatMul/include/ops_seq.hpp
tasks/seq/sarafanov_m_CanonMatMul/perf_tests/main.cpp
tasks/seq/sarafanov_m_CanonMatMul/src/CanonMatrix.cpp
tasks/seq/sarafanov_m_CanonMatMul/src/ops_seq.cpp

Алгоритм Кэнона - параллельный алгоритм умножения плотных, квадратных матриц. 
Пусть дана матрица **А** размерностью NxN, и матрица **В** такой же размерности. Результатом их произведения будет считаться некоторая матрица **С**. Стандартный алгоритм умножения матриц обладает вычислительной сложностью O(n^3), но благодаря многопоточности этот процесс можно сделать намного эффективнее. Одним из алгоритмов, построенных на использовании многопоточности, является алгоритм Кэнона.
Суть алгоритма заключается в следующем: создается некоторое количество исполняющих потоков, каждый из которых сдвигает элементы матрицы (сдвиг на 1 элемент влево по строкам для матрицы А и на 1 элемент вверх для матрицы В). После сдвига матрицы умножаются поэлементно, а результат записывается в результирующую матрицу …

Сарафанов Максим. Вариант 1. Технология SEQ. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона

---

tasks/seq/chizhov_m_trapezoid_method/func_tests/main.cpp
tasks/seq/chizhov_m_trapezoid_method/include/ops_seq.hpp
tasks/seq/chizhov_m_trapezoid_method/perf_tests/main.cpp
tasks/seq/chizhov_m_trapezoid_method/src/ops_seq.cpp

Метод трапеций — это численный метод интегрирования, который может быть применен в многомерном контексте. Он начинается с определения границ интегрирования и разбиения области на заданное количество сегментов по всем измерениям.
Для каждого узла вычисляется его положение в многомерном пространстве, и в этих точках определяется значение функции. Каждому узлу присваивается вес, который отражает его значимость: краевым узлам присваивается меньший вес, а внутренним — больший. Это соответствует идее метода трапеций, где значения на краях имеют меньшую значимость.
В конце процесса метод суммирует произведения значений функции на соответствующих весах и умножает результат на шаги, деленные на два.

Чижов Максим. Задача 1. Вариант 10. Технология SEQ. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).

---

tasks/seq/korotin_e_crs_multiplication/func_tests/main.cpp
tasks/seq/korotin_e_crs_multiplication/include/ops_seq.hpp
tasks/seq/korotin_e_crs_multiplication/perf_tests/main.cpp
tasks/seq/korotin_e_crs_multiplication/src/ops_seq.cpp

Матрицы хранятся в виде 3х векторов (val, col, row index)
В векторе val хранятся все ненулевые элементы матрицы построчно.
В векторе col того же размера, что и val хранятся номера столбцов, в которых лежат соответствующие элементы из val.
Массив row index представляет собой массив префиксных сумм массива, в котором на i+1 месте лежит количество ненулевых элементов в i-й строке матрицы.
На вход подаются матрицы А и В, хранящиеся в таком виде, для удобного перемножения матриц B транспонируется и умножение происходит в виде "строка на строку", с размещением полученных элементов в матрице-результате.

Коротин Егор. Задача 1. Вариант 4. Технология SEQ. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – строковый (CRS).

---

tasks/seq/sharamygina_i_multi_dim_monte_carlo/func_tests/func_tests.cpp
tasks/seq/sharamygina_i_multi_dim_monte_carlo/include/ops_seq.h
tasks/seq/sharamygina_i_multi_dim_monte_carlo/perf_tests/perf_tests.cpp
tasks/seq/sharamygina_i_multi_dim_monte_carlo/src/ops_seq.cpp

Код реализует многомерное интегрирование методом Монте-Карло в классе MultiDimMonteCarloTask.
Предобработка: Извлекает границы интегрирования, функцию и количество итераций из входных данных.
Валидация: Проверяет корректность входных данных.
Выполнение: Генерирует случайные точки, вычисляет значения функции и итоговый результат, учитывая объем области интегрирования.
Постобработка: Сохраняет результат в выходные данные.
Таким образом, код позволяет оценивать многомерные интегралы с использованием случайных выборок.

Шарамыгина Ирина. Вариант 12. Технология SEQ. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/seq/Konstantinov_I_Sort_Batcher/func_tests/main.cpp
tasks/seq/Konstantinov_I_Sort_Batcher/include/ops_seq.hpp
tasks/seq/Konstantinov_I_Sort_Batcher/perf_tests/main.cpp
tasks/seq/Konstantinov_I_Sort_Batcher/src/ops_seq.cpp

Программа сортирует массив чисел с плавающей точкой (типа `double`) методом поразрядной сортировки. Процесс состоит из нескольких этапов: 
1. **Валидация:** Проверяется, что входной и выходной массивы имеют одинаковый размер. Если размеры не совпадают, программа должна сообщить об ошибке и прекратить работу. 
2. **Препроцессинг (Предварительная обработка):** Входные данные копируются во внутреннюю структуру данных программы (класс задачи). Это делается для удобства обработки и предотвращения случайных изменений исходных данных. 
3 **Обработка (Сортировка):** Здесь происходит основная часть работы — собственно, поразрядная сортировка чисел с плавающей точкой. Поразрядная сортировка работает по принципу последовательного распределения элементов по "корзинам" в зависимости от значения …

Константинов Илья. Вариант 20. Технология SEQ. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

---

tasks/seq/malyshev_v_radix_sort/func_tests/main.cpp
tasks/seq/malyshev_v_radix_sort/include/ops_seq.hpp
tasks/seq/malyshev_v_radix_sort/perf_tests/main.cpp
tasks/seq/malyshev_v_radix_sort/src/ops_seq.cpp

1. **Разделение на отрицательные и положительные числа**:
- Массив разделяется на две части с помощью `std::ranges::partition`. Отрицательные числа помещаются в начало массива, положительные — в конец.
2. **Обработка отрицательных чисел**:
- Каждое отрицательное число преобразуется в положительное с помощью инверсии знакового бита (XOR с `0x8000000000000000`).
- Применяется поразрядная сортировка для модифицированных значений.
- После сортировки биты восстанавливаются, и массив отрицательных чисел переворачивается (так как они были отсортированы в обратном порядке).
3. **Обработка положительных чисел**:
- Положительные числа сортируются напрямую с использованием поразрядной сортировки без модификации битов.
4. **Слияние частей**:
- Отрицательные (уже отсортированные в убывающем порядке) и …

Малышев Владимир. SEQ. Вариант 19. "Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием."

---

tasks/omp/moiseev_a_mult_mat/func_tests/main.cpp
tasks/omp/moiseev_a_mult_mat/include/ops_omp.hpp
tasks/omp/moiseev_a_mult_mat/perf_tests/main.cpp
tasks/omp/moiseev_a_mult_mat/src/ops_omp.cpp

Описание OMP версии:
Данные загружаются из task_data в векторы matrix_a_ и matrix_b_, представляющие входные матрицы. Создается вектор для результата matrix_c_. Вычисляются размеры матриц, размер блока и количество блоков.
В цикле происходит умножение матриц с использованием блочной схемы. Для параллелизации внешних циклов по блокам (i_block и j_block) применяется директива #pragma omp parallel for. Это позволяет выполнять умножение блоков одновременно в нескольких потоках, ускоряя вычисления на многоядерных процессорах. Результаты суммируются в матрицу matrix_c_.

Моисеев Артём. Задача 2. Вариант 2. Технология OMP. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

---

tasks/seq/kharin_m_multidimensional_integral_calc/func_tests/main.cpp
tasks/seq/kharin_m_multidimensional_integral_calc/include/ops_seq.hpp
tasks/seq/kharin_m_multidimensional_integral_calc/perf_tests/main.cpp
tasks/seq/kharin_m_multidimensional_integral_calc/src/ops_seq.cpp

Реализация представляет последовательное вычисление многомерных интегралов методом прямоугольников. Код принимает значения функции на равномерной сетке произвольной размерности, размеры сетки по каждому измерению и шаги интегрирования, а затем вычисляет приближённый интеграл как сумму всех значений функции, умноженную на элемент объёма (произведение шагов). Использование типа double обеспечивает высокую точность вычислений, а структура поддерживает любые размерности благодаря динамическому определению сетки и шагов.
Процесс разбит на этапы: PreProcessingImpl извлекает входные данные и проверяет их согласованность, ValidationImpl контролирует корректность структуры входов и выходов, RunImpl выполняет основное вычисление суммы и объёма, а PostProcessingImpl записывает результат.

Харин Матвей. Задача 1. Вариант 9. Технология SEQ. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/seq/solovyev_d_shell_sort_simple/func_tests/main.cpp
tasks/seq/solovyev_d_shell_sort_simple/include/ops_seq.hpp
tasks/seq/solovyev_d_shell_sort_simple/perf_tests/main.cpp
tasks/seq/solovyev_d_shell_sort_simple/src/ops_seq.cpp

Сортировка Шелла с простым слиянием является модифицированной версией сортировки вставками, где элементы массива сортируются с использованием различных интервалов между элементами.
Начальный интервал, `gap` - изначально равен длины массива.
Сортируются все подмассивы используя сортировку вставками, индексы подмассивов разделены интервалом `gap`.
После этого, интервал уменьшается в два раза и происходит повторная сортировка.
Алгоритм продолжает работу, пока длина интервала не будет равна 1, при длине интервала 1 массив является отсортированным.

Соловьев Данила. Задача 1. Вариант 15. Технология SEQ. Сортировка Шелла с простым слиянием.

---

tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/func_tests/main.cpp
tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/include/ops_seq.hpp
tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/src/ops_seq.cpp

**Description**: Prepares the data for executing the algorithm. Initializes matrices \( A \), \( B \), and \( C \), and copies input data into the corresponding vectors.
**Main Steps**:
- Extracts the matrix size \( N \) and block size `block_size` from the input data.
- Initializes vectors \( A \), \( B \), and \( C \) - result matrix.
- Copies data from input arrays into vectors \( A \) and \( B \).
---
**Description**: Validates the correctness of the input data.
**Main Steps**:
- Checks that the number of input and output data matches the expected values.
- Ensures that the sizes of matrices \( A \) and \( B \) are \( N \times N \).
- Verifies that the block size `block_size` is greater than 0.
---
**Description**: Executes the Fox algorithm for matrix multiplication.
**Main Steps**: …

Лысов Иван. Задача 1. Вариант 2. Технология SEQ. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

---

tasks/seq/moiseev_a_mult_mat/func_tests/main.cpp
tasks/seq/moiseev_a_mult_mat/include/ops_seq.hpp
tasks/seq/moiseev_a_mult_mat/perf_tests/main.cpp
tasks/seq/moiseev_a_mult_mat/src/ops_seq.cpp

Описание seq версии:
Данные загружаются из task_data в два вектора matrix_A_ и matrix_B_, которые представляют собой входные матрицы. Затем создается вектор для матрицы результата matrix_C_. Также вычисляются размеры матриц и устанавливаются размер блока и количество блоков.
В цикле происходит умножение матриц с использованием блоков. Каждая матрица разбивается на блоки, и для каждого блока выполняется умножение соответствующих подматриц. Результаты складываются в соответствующие элементы матрицы matrix_C_.

Моисеев Артём. Задача 1. Вариант 2. Технология SEQ. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

---

tasks/seq/plekhanov_d_dijkstra/func_tests/main.cpp
tasks/seq/plekhanov_d_dijkstra/include/ops_seq.hpp
tasks/seq/plekhanov_d_dijkstra/perf_tests/main.cpp
tasks/seq/plekhanov_d_dijkstra/src/ops_seq.cpp

Алгоритм Дейкстры предназначен для нахождения кратчайших путей от заданной начальной вершины до всех остальных вершин в графе.
Для этого создается вектор списков смежности `adj_list`, где каждый элемент `adj_list[i]` представляет собой вектор пар `<dest, weight>`, указывающих на ребра, исходящие из вершины `i`. Данные о графе из `graph_data_` преобразуются в представление списка смежности. В этом формате данные о ребрах хранятся последовательно, а значение `-1` используется в качестве разделителя между списками ребер для разных вершин.
Алгоритм Дейкстры работает следующим образом:
- Создается вектор списков смежности `adj_list`, где каждый элемент представляет собой вектор пар `<dest, weight>`, указывающих на ребра, исходящие из вершины.
- Для каждой вершины …

Плеханов Даниил. Задача 1. Вариант 21. Технология SEQ. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры).

---

tasks/omp/chernykh_a_multidimensional_integral_rectangle/func_tests/main.cpp
tasks/omp/chernykh_a_multidimensional_integral_rectangle/include/ops_omp.hpp
tasks/omp/chernykh_a_multidimensional_integral_rectangle/perf_tests/main.cpp
tasks/omp/chernykh_a_multidimensional_integral_rectangle/src/ops_omp.cpp

Задача **вычисления многомерного интеграла методом правых прямоугольников** направлена на численное определение значения интеграла функции нескольких переменных на заданных границах.
- Устанавливаются параметры интегрирования — границы по каждому измерению и количество шагов.
- Проверяется корректность входных данных: границы интегрирования должны быть корректно заданы (левая граница меньше правой), а количество шагов по каждому измерению должно быть положительным.
2. **Интегрирование** (Параллельное выполнение):
- Все точки многомерной сетки обрабатываются параллельно с использованием OpenMP.
- Для каждой точки вычисляется значение функции `func_`, представляющей подынтегральную функцию.
- Для корректного суммирования значений функции из разных потоков используется …

Черных Андрей. Задача 2. Вариант 9. Технология OMP. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/seq/kapustin_i_jarv_alg/func_tests/main.cpp
tasks/seq/kapustin_i_jarv_alg/include/ops_seq.hpp
tasks/seq/kapustin_i_jarv_alg/perf_tests/main.cpp
tasks/seq/kapustin_i_jarv_alg/src/ops_seq.cpp

Алгоритм получает на вход множество точек, представленных в виде вектора пар координат. В первую очередь находится начальная точка — это точка с наименьшей координатой y, а при равенстве y — с наименьшим x. Она гарантированно принадлежит выпуклой оболочке и становится стартовой для построения границы. Далее алгоритм проходит по всем точкам и выбирает следующую точку, которая образует наибольший левый поворот относительно текущей. Для этого используется векторное произведение, которое позволяет определить положение точки относительно текущего ребра. Если точка находится левее, она становится кандидатом на включение в оболочку. Если точки коллинеарны, выбирается наиболее удаленная от текущей. Этот процесс продолжается, пока алгоритм не вернется в начальную точку, формируя замкнутый контур …

Капустин Иван. Вариант 23. Технология SEQ. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/seq/muhina_m_dijkstra/perf_tests/main.cpp

[FIX Perf Tests] Мухина Маргарита. Вариант 21. Технология SEQ. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры)

---

tasks/seq/malyshev_a_increase_contrast_by_histogram/perf_tests/main.cpp

[FIX] Малышев Антон. Задача 1. Вариант 28. Технология SEQ. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы. 

---

tasks/omp/ermolaev_v_graham_scan/func_tests/main.cpp
tasks/omp/ermolaev_v_graham_scan/include/ops_omp.hpp
tasks/omp/ermolaev_v_graham_scan/perf_tests/main.cpp
tasks/omp/ermolaev_v_graham_scan/src/ops_omp.cpp

Части программы подвергшиеся параллелизму:
1. Параллельная сортировка (ParallelSort)
2. Поиск минимального элемента (IndexOfMinElement)
3. Проверка коллинеарности точек (IsAllCollinear)
4. Проверка идентичности точек (IsAllSame)
Сам алгоритм Грэхема выполняется последовательно, так как он имеет существенные зависимости между итерациями. Распараллеливание сосредоточено на подготовительных шагах, где параллелизм наиболее эффективен.

Ермолаев Владислав. Задача 1. Вариант 22. Технология OMP. Построение выпуклой оболочки – проход Грэхема.

---

tasks/omp/kalyakina_a_Shell_with_simple_merge/func_tests/main.cpp
tasks/omp/kalyakina_a_Shell_with_simple_merge/include/ops_omp.hpp
tasks/omp/kalyakina_a_Shell_with_simple_merge/perf_tests/main.cpp
tasks/omp/kalyakina_a_Shell_with_simple_merge/src/ops_omp.cpp

**Принцип работы алгоритма (сортировка по неубыванию):**
**1. Расчет длины подмассивов:** массив разбивается по возможности равномерно на несколько подмассивов для параллельной сортировки по алгоритму Шелла.
**2. Выбор интервалов:** выбрана последовательность Седжвика (1, 5, 19, 41, 109, 209, ...). Расчет элементов последовательности происходит до момента, когда следующий элемент последовательности, умноженный на 3, будет больше или равен размеру сортируемого подмассива.
**3. Параллельная сортировка подмассивов:** используется сортировка Шелла. Сортируются элементы, которые находятся на расстоянии текущего интервала друг от друга, после чего происходит уменьшение интервала: выбираем следующий элемент последовательности Седжвика (в меньшую сторону), пока не дойдем до 1.
**4. Параллельное …

Калякина Анастасия. Задача 1. Вариант 15. Технология OMP. Сортировка Шелла с простым слиянием. 

---

tasks/omp/shurigin_s_integrals_square_OMP/func_tests/main.cpp
tasks/omp/shurigin_s_integrals_square_OMP/include/ops_omp.hpp
tasks/omp/shurigin_s_integrals_square_OMP/perf_tests/main.cpp
tasks/omp/shurigin_s_integrals_square_OMP/src/ops_omp.cpp

**Этап 1: Предобработка данных**
> Инициализация внутренних переменных: нижнего и верхнего предела, количества разбиений, результата.
> 
> Проверка корректности входных данных и преобразование указателей.
**Этап 2: Валидация данных**
> Проверка структуры данных задачи: количество входных и выходных элементов.
> 
> Удостовериться в соответствии типов и размеров входных и выходных данных ожидаемым значениям.
**Этап 3: Выполнение вычислений**
> 
> Определение функции интегрирования, если она задана.
> 
> Расчёт интеграла методом квадратур: 
> 1. Разбиение интервала на заданное количество частей.
> 2. Используем директиву ` #pragma omp parallel for reduction(+:result)` для распараллеливания цикла.
**Этап 4: Постобработка данных**
> Запись результата в выходной буфер.
> 
> Проверка …

Шурыгин Сергей. Задача 2. Вариант 9. Технология OMP. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/seq/vladimirova_j_m_monte_karlo_seq/func_tests/main.cpp

Заметила, что у кого-то не прошел по времени мой тест, решила заранее сделать фикс - уменьшить кол-во вычислений и точность, теперь должно быть быстрее

FIX Владимирова Юлия. Задача 1. Вариант 12. Технология SEQ. Вычисление многомерных интегралов методом Монте-Карло.

---

tasks/omp/lavrentiev_A_CCS_OMP/func_tests/main.cpp
tasks/omp/lavrentiev_A_CCS_OMP/include/ops_omp.hpp
tasks/omp/lavrentiev_A_CCS_OMP/perf_tests/main.cpp
tasks/omp/lavrentiev_A_CCS_OMP/src/ops_omp.cpp

Работа алгоритма:
Validation: Провожу проверку на совпадение количества строк первой матрицы и количество столбцов второй матрицы, также сравниваю размер входного и выходного векторов.
Pre_processing: Считываю матрицы, которые необходимо перемножить из task_data, попутно перевожу их в разреженный вид. Для этого была создана структура Sparse, содержащая 3 вектора и std::pair для хранения размеров
Run: В функции Run вызываю функцию перемножения матриц. Внутри функции умножения происходит транспонирование первой матрицы (что необходимо для более эффективной реализации умножения), после чего элементы матриц умножаются с помощью циклов. 
ИЗМЕНЕНИЯ:
**Сами циклы были помещены в параллельную секцию, что значительно увеличило производительность алгоритма. Скорость выполнения тестов на 3-ех …

Лаврентьев Алексей. Задача 2. Вариант 5. Технология OMP Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – столбцовый (CCS)

---

tasks/omp/mezhuev_m_bitwise_integer_sort_with_simple_merge_omp/func_tests/main.cpp
tasks/omp/mezhuev_m_bitwise_integer_sort_with_simple_merge_omp/include/ops_omp.hpp
tasks/omp/mezhuev_m_bitwise_integer_sort_with_simple_merge_omp/perf_tests/main.cpp
tasks/omp/mezhuev_m_bitwise_integer_sort_with_simple_merge_omp/src/ops_omp.cpp

Поразрядная сортировка — это алгоритм некомпаративной сортировки, который упорядочивает числа, рассматривая их разряды (цифры) поочередно, начиная с младших и двигаясь к старшим. В данной задаче используется параллельная реализация с OpenMP, что ускоряет процесс сортировки на многопоточных системах.
Алгоритм сначала выполняет поразрядную сортировку, а затем применяет простое слияние для объединения отсортированных частей. В данной реализации OpenMP применяется для:
Параллельного подсчета количества элементов по текущему разряду (используется #pragma omp parallel).
Префиксной суммы для определения индексов (используется #pragma omp critical).
Распределения элементов в новый массив в порядке сортировки (используется #pragma omp parallel for).

Межуев Максим Задача 17. Технология OMP. Поразрядная сортировка для целых чисел с простым слиянием.

---

tasks/omp/kolokolova_d_integral_simpson_method_omp/func_tests/main.cpp
tasks/omp/kolokolova_d_integral_simpson_method_omp/include/ops_omp.hpp
tasks/omp/kolokolova_d_integral_simpson_method_omp/perf_tests/main.cpp
tasks/omp/kolokolova_d_integral_simpson_method_omp/src/ops_omp.cpp

SEQ: Метод Симпсона заключается в нахождение интеграла путем аппроксимации интегрируемой функции параболами (в случае одной неизвестной), параболоидами (в случае с двумя неизвестными) и т.д. Входными данными являются функция, которую мы интегрируем, границы интегралов и сколько шагов нужно сделать для каждой из неизвестных (то есть на сколько частей по каждой из осей мы разбиваем функцию). В валидации мы проверяем, что все данные передаются, а также что границы интегралов правильно указаны (то есть, что нижняя граница меньше верхней). После этого в RunImpl() мы находим длину шага для каждой из осей и все их точки. После чего с помощью метода findFunctionValue() находим значение функции в каждой точке, а с помощью метода findCoeff() находим коэффициенты, на которые необходимо будет …

Колоколова Дарья. Вариант 11. Технология OMP. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона).

---

tasks/omp/korotin_e_crs_multiplication/func_tests/main.cpp
tasks/omp/korotin_e_crs_multiplication/include/ops_omp.hpp
tasks/omp/korotin_e_crs_multiplication/perf_tests/main.cpp
tasks/omp/korotin_e_crs_multiplication/src/ops_omp.cpp

Матрицы хранятся в виде 3х векторов (val, col, row index)
В векторе val хранятся все ненулевые элементы матрицы построчно.
В векторе col того же размера, что и val хранятся номера столбцов, в которых лежат соответствующие элементы из val.
Массив row index представляет собой массив префиксных сумм массива, в котором на i+1 месте лежит количество ненулевых элементов в i-й строке матрицы.
На вход подаются матрицы А и В, хранящиеся в таком виде, для удобного перемножения матриц B транспонируется и умножение происходит в виде "строка на строку", с размещением полученных элементов в матрице-результате.
Ускорение происходит за счет распараллеливания цикл, проходящего по матрице А (#pragma omp parallel for)

Коротин Егор. Задача 1. Вариант 4. Технология OMP. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – строковый (CRS).

---

tasks/seq/muhina_m_dijkstra/perf_tests/main.cpp

Исправлены perf tests. Добавлена проверка правильности результата

[FIX Perf tests] Мухина Маргарита. Вариант 21. Технология SEQ. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры) 

---

tasks/seq/opolin_d_radix_sort_betcher_merge/func_tests/main.cpp
tasks/seq/opolin_d_radix_sort_betcher_merge/include/ops_seq.hpp
tasks/seq/opolin_d_radix_sort_betcher_merge/perf_tests/main.cpp
tasks/seq/opolin_d_radix_sort_betcher_merge/src/ops_seq.cpp

Алгоритм поразрядной сортировки:
1. разделяем исходный вектор на вектора с положительными и отрицательными значениями.
2. определение максимального разряда
3. применяем поразрядную сортировку используя метод LSD(повторяем 3.1-3.2 от младшего к старшему разряду):
3.1) создается 10 корзин (от 0 до 9) для распределения элементов по текущему разряду.
3.2) переупорядочиваем элементы на основе распределения по корзинам, сохраняя относительный порядок при равенстве разрядов
4. для вектора отрицательных чисел порядок элементов реверсируется
5. объединяем в итоговый вектор вектора с положительными и отрицательными значениями
Четно-нечетное слияние Бэтчера в последовательной версии не имеет смысла, так как слияние Бэтчера предназначено для параллельного слияния предварительно отсортированных …

Ополин Дмитрий. Вариант 18. Технология SEQ. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера.

---

tasks/omp/milovankin_m_histogram_stretching/func_tests/main.cpp
tasks/omp/milovankin_m_histogram_stretching/include/ops_omp.hpp
tasks/omp/milovankin_m_histogram_stretching/perf_tests/main.cpp
tasks/omp/milovankin_m_histogram_stretching/src/ops_omp.cpp

Алгоритм линейно растягивает гистограмму изображения таким образом, чтобы минимальное значение пикселя было равно нулю, а максимальное 255. Промежуточные значения также меняются в соответствии с минимумом и максимумом.
В начале алгоритма параллельно ищется минимум min и максимум max, где каждый поток обрабатывает свою часть изображения и находит локальные min и max значения, а затем в критической секции обновляются глобальные значения. Итоговое изображение получается параллельным применением к каждому пикселю формулы:
value = ((value - min) * 255 + delta/2) / delta,
где delta = max - min, а добавление delta/2 в числитель обеспечивает правильное округление.

Милованкин Максим. Задача 2. Вариант 28. Технология OMP. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы.

---

tasks/omp/kolodkin_g_multiplication_matrix_CRS/func_tests/main.cpp
tasks/omp/kolodkin_g_multiplication_matrix_CRS/include/ops_omp.hpp
tasks/omp/kolodkin_g_multiplication_matrix_CRS/perf_tests/main.cpp
tasks/omp/kolodkin_g_multiplication_matrix_CRS/src/ops_omp.cpp

Описание параллельной задачи:
На вход подается вектор, который содержит данные двух разреженных матриц.
Preproccessing: на этом этапе считывается входной вектор, разделяется на две части(каждый подвектор соответствует данным одной из двух матриц), после чего каждый вектор с помощью функции парсится в структуру SparseMatrixCRS. На выходе получаются две объекта типа SparseMatrixCRS, которые представляют матрицы, которые требуется перемножить.
Validation: проверяется, что количество столбцов первой матрицы равно количеству строк второй матрицы. Если это условие не выполнено, то умножение невозможно.
Run: параллелизм осуществляется за счет распараллеливания цикла с помощью OpenMP. Для каждой строки матрицы A создается вектор temp_results, который хранит текущие результаты умножения строки …

Колодкин Григорий. Вариант 6. OMP. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матриц - строковый(CRS).

---

tasks/omp/oturin_a_gift_wrapping/func_tests/main.cpp
tasks/omp/oturin_a_gift_wrapping/include/ops_omp.hpp
tasks/omp/oturin_a_gift_wrapping/perf_tests/main.cpp
tasks/omp/oturin_a_gift_wrapping/src/ops_omp.cpp

На валидации только отсеиваются случаи, когда количество точек меньше трёх.
Цель алгоритма - построить такую оболочку, чтобы все точки были либо внутри оболочки, либо были её частью.
Сначала отыскивается самая левая точка (если их несколько на одной координате, то берётся самая высокая). Эта точка добавляется в output_. К этой точке создаётся отрезок с новой точкой, спущенный вертикально вниз относительно первой точки (этот отрезок не будет включён в вывод). Далее ищется наибольший угол этого отрезка и точек из input_. Полученная точка добавляется в output_. Далее начинается цикл до тех пор, пока алгоритм не дойдёт до стартовой точки и не замкнёт оболочку: тоже ищется наибольший угол между двумя последними точками, наилучшая точка добавляется в вывод.
Ещё, если угол …

Отурин Александр. Вариант 23. Технология OMP. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/omp/plekhanov_d_dijkstra/func_tests/main.cpp
tasks/omp/plekhanov_d_dijkstra/include/ops_omp.hpp
tasks/omp/plekhanov_d_dijkstra/perf_tests/main.cpp
tasks/omp/plekhanov_d_dijkstra/src/ops_omp.cpp

---
- **Список смежности (adj_list)**
- Вектор списков, где `adj_list[i]` — вектор пар `<dest, weight>`
- Пара:  
- **dest** — номер целевой вершины  
- **weight** — вес ребра
- **Преобразование данных**
- Исходные данные берутся из массива `graph_data_`
- Данные хранятся последовательно
- Значение `-1` (или `kEndOfVertexList`) используется как разделитель между списками ребер разных вершин
---
- **Создание списка смежности**
- Выделяется место для каждой вершины (например, для 8 ребер)
- **Преобразование графа**
- Последовательное преобразование данных из `graph_data_` в список смежности
- При встрече значения `kEndOfVertexList` переход к следующей вершине
- Если вес ребра отрицательный — выход с ошибкой (`false`)
- **Инициализация расстояний**
- Расстояние до начальной вершины …

Плеханов Даниил. Задача 1. Вариант 21. Технология OMP. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры).

---

tasks/omp/chizhov_m_trapezoid_method/func_tests/main.cpp
tasks/omp/chizhov_m_trapezoid_method/include/ops_omp.hpp
tasks/omp/chizhov_m_trapezoid_method/perf_tests/main.cpp
tasks/omp/chizhov_m_trapezoid_method/src/ops_omp.cpp

Этот код реализует параллельный метод трапеций для численного интегрирования многомерных функций с использованием OpenMP. Он разбивает область интегрирования на равные отрезки по каждой размерности. Затем создается сетка узлов, и для каждого узла вычисляются веса: граничные узлы имеют вес 1.0, а внутренние — 2.0. Код использует параллельные вычисления для суммирования значений функции в узлах с учетом этих весов, что делает процесс более быстрым. Он поддерживает произвольное количество размерностей, что позволяет работать как с одномерными, так и с многомерными функциями. В конце результат округляется до двух знаков после запятой для удобства.

Чижов Максим. Вариант 10. Технология OMP. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).

---

tasks/omp/shkurinskaya_e_bin_labeling/func_tests/main.cpp
tasks/omp/shkurinskaya_e_bin_labeling/include/ops_omp.hpp
tasks/omp/shkurinskaya_e_bin_labeling/perf_tests/main.cpp
tasks/omp/shkurinskaya_e_bin_labeling/src/ops_omp.cpp

Этот алгоритм реализует параллельный метод маркировки связных компонент на бинарном изображении с использованием OpenMP. В первом этапе каждому пикселю с значением 1 присваивается уникальный индекс, создавая отдельные компоненты. Во втором этапе для каждого пикселя с 1 проверяются его восемь соседей, и компоненты объединяются. В третьем этапе выполняется сжатие путей для оптимизации структуры объединённых компонент. OpenMP используется для распараллеливания циклов, ускоряя обработку больших изображений.

Шкуринская Елена. Вариант 29. Технология OMP. Маркировка компонент на бинарном изображении.

---

.github/workflows/main.yml
tasks/stl/example/perf_tests/main.cpp

- Set missing OMP_NUM_THREADS env variable
- Fix fail on error strategy

[CI] Fix perf tests run

---

tasks/all/rams_s_vertical_gauss_3x3/perf_tests/main.cpp
tasks/omp/rams_s_vertical_gauss_3x3/perf_tests/main.cpp
tasks/seq/rams_s_vertical_gauss_3x3/perf_tests/main.cpp
tasks/tbb/rams_s_vertical_gauss_3x3/perf_tests/main.cpp

Уменьшен размер входных данных, чтобы время выполнения тестов не превышало лимит.

fix: Рамс Сергей. Вариант 25. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.‎

---

tasks/tbb/nikolaev_r_hoare_sort_simple_merge/func_tests/main.cpp
tasks/tbb/nikolaev_r_hoare_sort_simple_merge/include/ops_tbb.hpp
tasks/tbb/nikolaev_r_hoare_sort_simple_merge/perf_tests/main.cpp
tasks/tbb/nikolaev_r_hoare_sort_simple_merge/src/ops_tbb.cpp

Используется функция `ppc::util::GetPPCNumThreads()`, чтобы определить количество доступных потоков, которое затем используется как число сегментов для сортировки.
Если возвращается 0, код принудительно устанавливает `num_segments` равным 1.
Также число сегментов ограничивается размером вектора, чтобы не создавать больше сегментов, чем элементов.
Вычисляется базовый размер сегмента (`segment_size`) как частное от деления общего количества элементов на число сегментов. Остаток от деления (`remainder`) распределяется по первым сегментам, чтобы суммарное распределение элементов было равномерным. Итогом цикла формируется вектор пар, где каждая пара содержит начальный и конечный индексы сегмента для сортировки.
Создается `oneapi::tbb::task_arena` с числом потоков, равным num_segments.
Внутри …

Николаев Роман. Вариант 13. Технология TBB. Сортировка Хоара с простым слиянием.

---

tasks/tbb/ermolaev_v_graham_scan/func_tests/main.cpp
tasks/tbb/ermolaev_v_graham_scan/include/ops_tbb.hpp
tasks/tbb/ermolaev_v_graham_scan/perf_tests/main.cpp
tasks/tbb/ermolaev_v_graham_scan/src/ops_tbb.cpp

Части программы подвергшиеся параллелизму:
1. Параллельная сортировка средствами TBB
2. Поиск минимального элемента (IndexOfMinElement)
3. Проверка коллинеарности точек (IsAllCollinear)
4. Проверка идентичности точек (IsAllSame)
Сам алгоритм Грэхема выполняется последовательно, так как он имеет существенные зависимости между итерациями. Распараллеливание сосредоточено на подготовительных шагах, где параллелизм наиболее эффективен.

Ермолаев Владислав. Задача 1. Вариант 22. Технология TBB. Построение выпуклой оболочки – проход Грэхема.

---

tasks/tbb/oturin_a_gift_wrapping/func_tests/main.cpp
tasks/tbb/oturin_a_gift_wrapping/include/ops_tbb.hpp
tasks/tbb/oturin_a_gift_wrapping/perf_tests/main.cpp
tasks/tbb/oturin_a_gift_wrapping/src/ops_tbb.cpp

На валидации только отсеиваются случаи, когда количество точек меньше трёх.
Цель алгоритма - построить такую оболочку, чтобы все точки были либо внутри оболочки, либо были её частью.
Сначала отыскивается самая левая точка (если их несколько на одной координате, то берётся самая высокая). Эта точка добавляется в output_. К этой точке создаётся отрезок с новой точкой, спущенный вертикально вниз относительно первой точки (этот отрезок не будет включён в вывод). Далее ищется наибольший угол этого отрезка и точек из input_. Полученная точка добавляется в output_. Далее начинается цикл до тех пор, пока алгоритм не дойдёт до стартовой точки и не замкнёт оболочку: тоже ищется наибольший угол между двумя последними точками, наилучшая точка добавляется в вывод. Если угол …

Отурин Александр. Вариант 23. Технология TBB. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/tbb/shvedova_v_graham_convex_hull/func_tests/main.cpp
tasks/tbb/shvedova_v_graham_convex_hull/include/ops_tbb.hpp
tasks/tbb/shvedova_v_graham_convex_hull/perf_tests/main.cpp
tasks/tbb/shvedova_v_graham_convex_hull/src/ops_tbb.cpp

Перед выполнением алгоритма производится проверка:
- Количество входных данных кратно 2 (так как передаются координаты точек).
- Число точек больше 2.
- Точки не лежат на одной прямой (проверяется с помощью `CheckCollinearity`).
- Выбирается точка с минимальной координатой `y` (если несколько, то с минимальным `x`).
- Используется угловая сортировка, где точки упорядочиваются относительно `pivot` по полярному углу.
- Дополнительно учитывается расстояние от `pivot`, чтобы отсортировать коллинеарные точки.
- Применяется проход по точкам с удалением "внутренних" точек (левый поворот или коллинеарность).
- Если следующая точка образует правый поворот, то предыдущая удаляется.
Для распараллеливания алгоритма используется Intel Threading Building Blocks (TBB). Основные этапы параллельной …

Шведова Виталина. Вариант 22. Технология TBB. Построение выпуклой оболочки – проход Грэхема.

---

tasks/tbb/chernykh_a_multidimensional_integral_rectangle/func_tests/main.cpp
tasks/tbb/chernykh_a_multidimensional_integral_rectangle/include/ops_tbb.hpp
tasks/tbb/chernykh_a_multidimensional_integral_rectangle/perf_tests/main.cpp
tasks/tbb/chernykh_a_multidimensional_integral_rectangle/src/ops_tbb.cpp

Задача **вычисления многомерного интеграла методом правых прямоугольников** направлена на численное определение значения интеграла функции нескольких переменных на заданных границах.
- Устанавливаются параметры интегрирования — границы по каждому измерению и количество шагов.
- Проверяется корректность входных данных: границы интегрирования должны быть корректно заданы (левая граница меньше правой), а количество шагов по каждому измерению должно быть положительным.
2. **Интегрирование**:
- Вычисляется общее количество точек многомерной сетки.
- Используется `oneapi::tbb::parallel_reduce` для параллельной обработки точек.
- Для каждой точки вычисляется значение функции `func_`, представляющей подынтегральную функцию.
- Результаты вычислений из разных задач …

Черных Андрей. Задача 3. Вариант 9. Технология TBB. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/omp/tyshkevich_a_hoare_simple_merge/perf_tests/main.cpp
tasks/seq/tyshkevich_a_hoare_simple_merge/perf_tests/main.cpp

Унифицировал тесты с тестами из следующей задачи

[FIX] Тышкевич Артём. Вариант 13. Сортировка Хоара с простым слиянием.

---

tasks/omp/korovin_n_qsort_batcher/perf_tests/main.cpp

#246 
изменены perf тесты согласно ревью
добавлен рандомный вектор с фиксированным seed

[FIX PERF] Коровин Никита. Вариант 14. Технология OMP. Сортировка Хоара с четно-нечетным слиянием Бэтчера. 

---

tasks/tbb/odintsov_m_multmatrix_cannon/func_tests/main.cpp
tasks/tbb/odintsov_m_multmatrix_cannon/include/ops_tbb.hpp
tasks/tbb/odintsov_m_multmatrix_cannon/perf_tests/main.cpp
tasks/tbb/odintsov_m_multmatrix_cannon/src/ops_tbb.cpp

Описание TBB версии
1. Определение размера блока:
- Используется функция GetBlockSize для вычисления размера блока.
2. Сдвиг начальных матриц A и B:
- Выполняется начальный сдвиг строк для матрицы A и столбцов для матрицы B с помощью функции InitializeShift.
3. Параллельное выполнение:
- Параллелим внешний цикл:
Используется tbb::parallel_for для распараллеливания работы по блокам, минимизируя накладные расходы на переключение потоков.
- Обработка блоков:
Каждый поток получает свой блок, копирует данные и выполняет умножение блоков матриц A и B.
- Обновление матрицы C:
Для синхронизации доступа к матрице C используется tbb::mutex, чтобы избежать гонок данных при обновлении результата.
4. Запись результата:
- Результат умножения записывается в матрицу C и сохраняется в …

Одинцов Михаил. Задача 1. Вариант 1. Технология TBB. Умножение плотных матриц,типа double,блочная схема, алгоритм Кэннона

---

tasks/tbb/kalyakina_a_Shell_with_simple_merge/func_tests/main.cpp
tasks/tbb/kalyakina_a_Shell_with_simple_merge/include/ops_tbb.hpp
tasks/tbb/kalyakina_a_Shell_with_simple_merge/perf_tests/main.cpp
tasks/tbb/kalyakina_a_Shell_with_simple_merge/src/ops_tbb.cpp

**Принцип работы алгоритма (сортировка по неубыванию):**
1. **Расчет длины подмассивов:** массив разбивается по возможности равномерно на несколько подмассивов для параллельной сортировки по алгоритму Шелла.
**2. Выбор интервалов:** выбрана последовательность Седжвика (1, 5, 19, 41, 109, 209, ...). Расчет элементов последовательности происходит до момента, когда следующий элемент последовательности, умноженный на 3, будет больше или равен размеру сортируемого подмассива.
**3. Параллельная сортировка подмассивов:** используется сортировка Шелла. Сортируются элементы, которые находятся на расстоянии текущего интервала друг от друга, после чего происходит уменьшение интервала: выбираем следующий элемент последовательности Седжвика (в меньшую сторону), пока не дойдем до 1.
**4. Параллельное …

Калякина Анастасия. Вариант 15. Технология TBB. Сортировка Шелла с простым слиянием.

---

tasks/omp/morozov_e_lineare_image_filtering_block_gaussian_omp/func_tests/main.cpp
tasks/omp/morozov_e_lineare_image_filtering_block_gaussian_omp/include/ops_omp.hpp
tasks/omp/morozov_e_lineare_image_filtering_block_gaussian_omp/perf_tests/main.cpp
tasks/omp/morozov_e_lineare_image_filtering_block_gaussian_omp/src/ops_omp.cpp

Линейная фильтрация изображений — это процесс применения к изображению линейного фильтра (например, свертки с ядром) для выполнения операций, таких как размытие, повышение резкости или выделение границ. В данном случае мы рассмотрим **блочное разбиение изображения** и применение **ядра Гаусса 3x3** для размытия изображения.
---
Для версии OpenMP оптимизируем циклы прохода по пикселям, присваивая каждому потоку свой ряд (линию)

Морозов Егор. Задача 1. Вариант 26. Технология OMP. Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3.

---

tasks/tbb/korneeva_e_sparse_matrix_mult_complex_ccs/func_tests/main.cpp
tasks/tbb/korneeva_e_sparse_matrix_mult_complex_ccs/include/ops_tbb.hpp
tasks/tbb/korneeva_e_sparse_matrix_mult_complex_ccs/perf_tests/main.cpp
tasks/tbb/korneeva_e_sparse_matrix_mult_complex_ccs/src/ops_tbb.cpp

**Задача:** Умножение двух разреженных матриц (sparse matrices) с комплексными числами, представленных в формате CCS (Compressed Column Storage). Умножение выполняется с использованием Intel TBB для параллелизации вычислений.
Логика работы:
1. **Разделение работы по столбцам:** Результирующая матрица формируется по столбцам, где каждый столбец вычисляется независимо от других. 
2. **Схема распараллеливания:** Набор столбцов результирующей матрицы распределяется между потоками с использованием `tbb::parallel_for`. Каждый поток обрабатывает свой диапазон столбцов, вычисляя ненулевые элементы и их строковые индексы.
3. **Особенности реализации:** Каждый поток работает с собственным временным буфером (`std::vector`) для хранения ненулевых элементов столбца, что исключает необходимость …

Корнеева Екатерина. Вариант 7. Технология TBB. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – столбцовый (CCS).

---

tasks/tbb/mezhuev_m_bitwise_integer_sort_with_simple_merge/func_tests/main.cpp
tasks/tbb/mezhuev_m_bitwise_integer_sort_with_simple_merge/include/ops_tbb.hpp
tasks/tbb/mezhuev_m_bitwise_integer_sort_with_simple_merge/perf_tests/main.cpp
tasks/tbb/mezhuev_m_bitwise_integer_sort_with_simple_merge/src/ops_tbb.cpp

Задача заключается в том, чтобы отсортировать массив целых чисел, используя поразрядную сортировку с простым слиянием. Для оптимизации работы алгоритм использует параллельные вычисления через TBB, что ускоряет процесс на многопроцессорных системах.
Алгоритм разделяет все числа на две группы: отрицательные и положительные. Для каждой группы выполняется поразрядная сортировка с использованием метода RadixSort, который сортирует числа по каждому разряду, начиная с младшего. После сортировки отрицательные числа инвертируются и добавляются в начало массива, а положительные числа — в конец.
Описание работы кода:
1.PreProcessingImpl:
В этом методе извлекаются входные данные, проверяется размер массива и определяется максимальное значение для последующего вычисления числа разрядов. …

Межуев Максим Задача 17. Технология TBB. Поразрядная сортировка для целых чисел с простым слиянием.

---

tasks/tbb/sozonov_i_image_filtering_block_partitioning/func_tests/main.cpp
tasks/tbb/sozonov_i_image_filtering_block_partitioning/include/ops_tbb.hpp
tasks/tbb/sozonov_i_image_filtering_block_partitioning/perf_tests/main.cpp
tasks/tbb/sozonov_i_image_filtering_block_partitioning/src/ops_tbb.cpp

**Стандартная свертка Гаусса (3×3):**
Ядро Гаусса 3x3 (нормированное) для σ=1 имеет вид: 
Каждому пикселю изображения ставится в соответствие новая величина, полученная как сумма произведений значений пикселей из окрестности 3×3 на коэффициенты ядра Гаусса.
Например, если центральный пиксель изображения **𝐼(𝑥, 𝑦)**, то его новое значение **𝐼′(𝑥, 𝑦)** будет: 
**Параллельная реализация:**
Для ускорения фильтрации изображений используется параллельная обработка блоков с помощью TBB.
**1. Разбиение на блоки**
- Задаётся размер блока `block_size` (например, 64×64).
- Изображение разбивается на прямоугольные блоки по координатам `i` и `j` с шагом `block_size`.
**2. Параллельная обработка блоков**
- Используется `tbb::task_group`, где каждая задача (`tg.run`) обрабатывает отдельный блок …

Созонов Илья. Вариант 26. Технология TBB. Линейная фильтрация изображений (блочное разбиение). Ядро Гаусса 3x3. 

---

tasks/tbb/kapustin_i_jarv_alg/func_tests/main.cpp
tasks/tbb/kapustin_i_jarv_alg/include/ops_tbb.hpp
tasks/tbb/kapustin_i_jarv_alg/perf_tests/main.cpp
tasks/tbb/kapustin_i_jarv_alg/src/ops_tbb.cpp

Построение выпуклой оболочки для множества точек. Сначала проверяется, что входные данные есть и точек достаточно. Затем находится самая левая (или самая верхняя из них) точка — с неё начинается построение оболочки. Алгоритм ищет следующую точку, которая образует наибольший поворот относительно текущей, и так шаг за шагом обходит все точки по кругу, пока не вернётся в начальную. На каждом шаге рассматриваются все точки, и этот перебор разбивается на части и выполняется параллельно с помощью TBB, чтобы ускорить вычисления. Из всех результатов выбирается наилучшая точка — та, что образует самый большой угол (или ближайшая при равенстве углов). После завершения результат копируется в выходной вектор.

Капустин Иван. Вариант 23. Технология TBB. Построение выпуклой оболочки – проход Джарвиса. 

---

tasks/omp/burykin_m_radix/func_tests/main.cpp
tasks/omp/burykin_m_radix/include/ops_omp.hpp
tasks/omp/burykin_m_radix/perf_tests/main.cpp
tasks/omp/burykin_m_radix/src/ops_omp.cpp
tasks/seq/burykin_m_radix/perf_tests/main.cpp
tasks/tbb/burykin_m_radix/perf_tests/main.cpp

Исправлены данные в perf тестах. Так же исправлены названия тестов и namespace в omp версии.

[FIX Perf] Бурыкин Михаил. Вариант 17.  Поразрядная сортировка для целых чисел с простым слиянием.

---

tasks/stl/plekhanov_d_dijkstra/func_tests/main.cpp
tasks/stl/plekhanov_d_dijkstra/include/ops_stl.hpp
tasks/stl/plekhanov_d_dijkstra/perf_tests/main.cpp
tasks/stl/plekhanov_d_dijkstra/src/ops_stl.cpp

Этот алгоритм находит кратчайшие пути от заданной начальной вершины до всех остальных вершин в графе, используя параллельное выполнение с помощью стандартных потоков (STL threads), атомарных переменных для расстояний и приоритетной очереди.
* Граф представлен в виде списка смежности, где для каждой вершины хранится список её соседей и весов рёбер.
* Входные данные графа преобразуются в этот список смежности.
* Расстояния от начальной вершины до всех остальных инициализируются как "бесконечность" (`INT_MAX`) с использованием атомарных переменных (`std::atomic<int>`). Расстояние до начальной вершины устанавливается равным 0.
* Используется приоритетная очередь (`std::priority_queue`) для хранения вершин, упорядоченных по текущему кратчайшему расстоянию. Пользовательский компаратор …

Плеханов Даниил. Задача 1. Вариант 21. Технология STL. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры).

---

tasks/stl/shvedova_v_graham_convex_hull/func_tests/main.cpp
tasks/stl/shvedova_v_graham_convex_hull/include/ops_stl.hpp
tasks/stl/shvedova_v_graham_convex_hull/perf_tests/main.cpp
tasks/stl/shvedova_v_graham_convex_hull/src/ops_stl.cpp

Перед выполнением алгоритма производится проверка:
- Количество входных данных кратно 2 (так как передаются координаты точек).
- Число точек больше 2.
- Точки не лежат на одной прямой (проверяется с помощью `CheckCollinearity`).
- Выбирается точка с минимальной координатой `y` (если несколько, то с минимальным `x`).
- Используется угловая сортировка, где точки упорядочиваются относительно `pivot` по полярному углу.
- Дополнительно учитывается расстояние от `pivot`, чтобы отсортировать коллинеарные точки.
- Применяется проход по точкам с удалением "внутренних" точек (левый поворот или коллинеарность).
- Если следующая точка образует правый поворот, то предыдущая удаляется.
Для распараллеливания сортировки точек по полярному углу используется std::thread и std::barrier.
---
- Каждому потоку …

Шведова Виталина. Вариант 22. Технология STL. Построение выпуклой оболочки – проход Грэхема. 

---

tasks/stl/odintsov_m_multmatrix_cannon/func_tests/main.cpp
tasks/stl/odintsov_m_multmatrix_cannon/include/ops_stl.hpp
tasks/stl/odintsov_m_multmatrix_cannon/perf_tests/main.cpp
tasks/stl/odintsov_m_multmatrix_cannon/src/ops_stl.cpp

Описание STL версии алгоритма умножения матриц по схеме Кэннона
1 Определение размера блока: Для вычисления оптимального размера блока используется функция GetBlockSize, которая находит наибольший делитель числа, меньший или равный его половине.
2 Сдвиг начальных матриц A и B:
Матрица A сдвигается по строкам с использованием функции ShiftRow.
Матрица B сдвигается по столбцам с помощью функции ShiftColumn.
Эти сдвиги необходимы для корректного распределения блоков матриц для умножения, следуя алгоритму Кэннона.
3 Параллельное выполнение: Для распараллеливания работы по блокам используется STL с помощью стандартных потоков (std::thread). Каждый поток обрабатывает свой блок, выполняя копирование данных и умножение блоков матриц A и B.
4 Обработка блоков: В каждом потоке происходит: …

Одинцов Михаил. Задача 1. Вариант 1. Технология STL. Умножение плотных матриц,типа double,блочная схема, алгоритм Кэннона

---

tasks/omp/shulpin_i_jarvis_passage/perf_tests/main.cpp

Фикс perf тестов из ревью stl версии
#608

[FIX] Шульпин Илья. Вариант 23. Технология OMP. Построение выпуклой оболочки – проход Джарвиса

---

tasks/tbb/shulpin_i_jarvis_passage/include/test_modules.hpp
tasks/tbb/shulpin_i_jarvis_passage/perf_tests/main.cpp
tasks/tbb/shulpin_i_jarvis_passage/src/test_modules.cpp

Фикс perf тестов из ревью stl версии
#608

[FIX] Шульпин Илья. Вариант 23. Технология TBB. Построение выпуклой оболочки – проход Джарвиса

---

tasks/stl/nasedkin_e_strassen_algorithm/func_tests/main.cpp
tasks/stl/nasedkin_e_strassen_algorithm/include/ops_stl.hpp
tasks/stl/nasedkin_e_strassen_algorithm/perf_tests/main.cpp
tasks/stl/nasedkin_e_strassen_algorithm/src/ops_stl.cpp

Реализация алгоритма Штрассена. Технология STL.

Наседкин Егор. Задача 1. Вариант 3. Технология STL. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

---

tasks/stl/chernykh_a_multidimensional_integral_rectangle/func_tests/main.cpp
tasks/stl/chernykh_a_multidimensional_integral_rectangle/include/ops_stl.hpp
tasks/stl/chernykh_a_multidimensional_integral_rectangle/perf_tests/main.cpp
tasks/stl/chernykh_a_multidimensional_integral_rectangle/src/ops_stl.cpp

Задача **вычисления многомерного интеграла методом правых прямоугольников** направлена на численное определение значения интеграла функции нескольких переменных на заданных границах.
- Устанавливаются параметры интегрирования — границы по каждому измерению и количество шагов.
- Проверяется корректность входных данных: левая граница для каждого измерения должна быть меньше правой, а количество шагов по каждому измерению должно быть положительным.
2. **Интегрирование**:
- Вычисляется общее количество точек многомерной сетки.
- Сетка делится на части, и каждая часть обрабатывается отдельным потоком (`std::thread`).
- Каждый поток вычисляет значения подынтегральной функции `func_` для своей части сетки.
- Результаты вычислений из разных потоков аккумулируются в векторе …

Черных Андрей. Задача 4. Вариант 9. Технология STL. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/stl/ermolaev_v_graham_scan/func_tests/main.cpp
tasks/stl/ermolaev_v_graham_scan/include/ops_stl.hpp
tasks/stl/ermolaev_v_graham_scan/perf_tests/main.cpp
tasks/stl/ermolaev_v_graham_scan/src/ops_stl.cpp

Части программы подвергшиеся параллелизму:
- Параллельная сортировка (ParallelSort)
- Проверка коллинеарности точек (IsAllCollinear)
Остальные части алгоритма, при распараллеливании особого прироста не получают, поэтому отставлены последовательными.

Ермолаев Владислав. Задача 1. Вариант 22. Технология STL. Построение выпуклой оболочки – проход Грэхема. 

---

tasks/stl/kalyakina_a_Shell_with_simple_merge/func_tests/main.cpp
tasks/stl/kalyakina_a_Shell_with_simple_merge/include/ops_stl.hpp
tasks/stl/kalyakina_a_Shell_with_simple_merge/perf_tests/main.cpp
tasks/stl/kalyakina_a_Shell_with_simple_merge/src/ops_stl.cpp

Принцип работы алгоритма (сортировка по неубыванию):
1. Расчет длины подмассивов: массив разбивается по возможности равномерно на несколько подмассивов для параллельной сортировки по алгоритму Шелла.
2. Выбор интервалов: выбрана последовательность Седжвика (1, 5, 19, 41, 109, 209, ...). Расчет элементов последовательности происходит до момента, когда следующий элемент последовательности, умноженный на 3, будет больше или равен размеру сортируемого подмассива.
3. Параллельная сортировка подмассивов: используется сортировка Шелла. Сортируются элементы, которые находятся на расстоянии текущего интервала друг от друга, после чего происходит уменьшение интервала: выбираем следующий элемент последовательности Седжвика (в меньшую сторону), пока не дойдем до 1.
4. Простое слияние подмассивов: два …

Калякина Анастасия. Вариант 15. Технология STL. Сортировка Шелла с простым слиянием.

---

tasks/stl/petrov_o_vertical_image_filtration/func_tests/main.cpp
tasks/stl/petrov_o_vertical_image_filtration/include/ops_stl.hpp
tasks/stl/petrov_o_vertical_image_filtration/perf_tests/main.cpp
tasks/stl/petrov_o_vertical_image_filtration/src/ops_stl.cpp

Данный проект представляет собой реализацию параллельной вертикальной фильтрации изображений с использованием многопоточности на основе std::threads.
Основные характеристики:
Назначение: применение гауссова фильтра к изображению для сглаживания или размытия
Структура входных данных: двумерный массив целых чисел, представляющий пиксели изображения
Основной алгоритм: применение гауссова фильтра с ядром 3×3 к каждому пикселю
Параллелизм: изображение разделяется на горизонтальные полосы, каждая обрабатывается отдельным потоком
Оптимизация: динамическое определение оптимального количества потоков в зависимости от размера изображения и доступных системных ресурсов
Класс TaskSTL реализует четыре основных этапа обработки:
Предварительная подготовка данных
Валидация входных параметров …

Петров Олег. Задача 1. Вариант 25. Технология STL. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.

---

tasks/seq/tyurin_m_matmul_crs_complex/perf_tests/main.cpp

Changing the range in pert_tests.

[FIX] Тюрин Михаил. Технология SEQ. 6 вариант. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – строковый (CRS).

---

tasks/stl/sarafanov_m_CanonMatMul/func_tests/main.cpp
tasks/stl/sarafanov_m_CanonMatMul/include/CanonMatrix.hpp
tasks/stl/sarafanov_m_CanonMatMul/include/ops_stl.hpp
tasks/stl/sarafanov_m_CanonMatMul/perf_tests/main.cpp
tasks/stl/sarafanov_m_CanonMatMul/src/CanonMatrix.cpp
tasks/stl/sarafanov_m_CanonMatMul/src/ops_stl.cpp

Структурные изменения: введена лямбда-функция multiplicator, в которой для каждого потока происходит умножение и последующее сложение сдвинутых матриц.
Распараллеливание с помощью STL: создан вектор потоков (std::thread), каждому из которых на вход подается лямбда-выражение multiplicator, начальный индекс итерации, сдвиг. После того, как все потоки выполнят свою работу, запускается цикл для вызова join(). На последнем этапе происходит суммирование матриц, полученных на каждом потоке. 
За счет разделения работы между потоками можно достичь ускорения выполнения алгоритма в 3-3.5 раза.

Сарафанов Максим. Вариант 1. Технология STL. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона

---

.github/workflows/pages.yml

Issue references and WA description: https://github.com/sphinx-doc/sphinx/issues/13533

Hotfix for sphinx issue in pages build

---

tasks/stl/shurigin_s_integrals_square/func_tests/main.cpp
tasks/stl/shurigin_s_integrals_square/include/ops_stl.hpp
tasks/stl/shurigin_s_integrals_square/perf_tests/main.cpp
tasks/stl/shurigin_s_integrals_square/src/ops_stl.cpp

Распределение работы:
> Одномерный случай: Общее количество интервалов интегрирования делится между доступными рабочими потоками.
> Многомерный случай (N > 1): Итерации только по самому внешнему измерению (первой координате) распределяются между рабочими потоками.
Выполнение в потоках:
> Каждый поток выполняет лямбда-функцию, которая обрабатывает назначенную ему часть работы.
> Многомерный случай: Внутри лямбда-функции потока вызывается последовательная рекурсивная функция (ComputeSequentialRecursive) для вычисления интеграла по всем внутренним измерениям.
Сбор результатов:
> Каждый поток передает свой вычисленный частичный результат.
> Основной поток ожидает и получает результаты от всех потоков.

Шурыгин Сергей. Задача 4. Вариант 9. Технология STL. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/omp/vershinina_a_hoare_sort_omp/perf_tests/main.cpp
tasks/seq/vershinina_a_hoare_sort_seq_disabled/perf_tests/main.cpp
tasks/stl/vershinina_a_hoare_sort_stl/func_tests/main.cpp
tasks/stl/vershinina_a_hoare_sort_stl/include/ops_stl.hpp
tasks/stl/vershinina_a_hoare_sort_stl/perf_tests/main.cpp
tasks/stl/vershinina_a_hoare_sort_stl/src/ops_stl.cpp

Функции Partition и HoareSort выполняют рекурсивную сортировку Хоара, разделяя массив на подмассивы. BatcherMergeBlocksStep выполняет слияние двух уже отсортированных блоков данных на месте с помощью std::inplace_merge. BatcherMerge итеративно объединяет отсортированные блоки с помощью алгоритма слияния Бэтчера. Если размер блока, деленный на step, превышает порог par_if_greater, функция создает заданное количество потоков и распараллеливает выполнение BatcherMergeBlocksStep между ними.

Вершинина Александра. Вариант 14. Технология STL. Сортировка Хоара с четно-нечетным слиянием Бэтчера.

---

tasks/stl/oturin_a_gift_wrapping/func_tests/main.cpp
tasks/stl/oturin_a_gift_wrapping/include/ops_stl.hpp
tasks/stl/oturin_a_gift_wrapping/perf_tests/main.cpp
tasks/stl/oturin_a_gift_wrapping/src/ops_stl.cpp

На валидации только отсеиваются случаи, когда количество точек меньше трёх.
Цель алгоритма - построить такую оболочку, чтобы все точки были либо внутри оболочки, либо были её частью.
Сначала отыскивается самая левая точка (если их несколько на одной координате, то берётся самая высокая). Эта точка добавляется в output_. К этой точке создаётся отрезок с новой точкой, спущенный вертикально вниз относительно первой точки (этот отрезок не будет включён в вывод). Далее ищется наибольший угол этого отрезка и точек из input_. Полученная точка добавляется в output_. Далее начинается цикл до тех пор, пока алгоритм не дойдёт до стартовой точки и не замкнёт оболочку: тоже ищется наибольший угол между двумя последними точками, наилучшая точка добавляется в вывод. Если угол …

Отурин Александр. Вариант 23. Технология STL. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/stl/kolodkin_g_multiplication_matrix_CRS/func_tests/main.cpp
tasks/stl/kolodkin_g_multiplication_matrix_CRS/include/ops_stl.hpp
tasks/stl/kolodkin_g_multiplication_matrix_CRS/perf_tests/main.cpp
tasks/stl/kolodkin_g_multiplication_matrix_CRS/src/ops_stl.cpp

Описание параллельной задачи:
На вход подается вектор, который содержит данные двух разреженных матриц.
Preproccessing: на этом этапе считывается входной вектор, разделяется на две части(каждый подвектор соответствует данным одной из двух матриц), после чего каждый вектор с помощью функции парсится в структуру SparseMatrixCRS. На выходе получаются две объекта типа SparseMatrixCRS, которые представляют матрицы, которые требуется перемножить.
Validation: проверяется, что количество столбцов первой матрицы равно количеству строк второй матрицы. Если это условие не выполнено, то умножение невозможно.
Run: параллелизм осуществляется за счет распараллеливания цикла с помощью потоков. Определяется количество потоков и создаются вектора для хранения потоков и локальных результатов. Дальше …

Колодкин Григорий. Вариант 6. STL. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – строковый (CRS).

---

tasks/stl/korotin_e_crs_multiplication/func_tests/main.cpp
tasks/stl/korotin_e_crs_multiplication/include/ops_stl.hpp
tasks/stl/korotin_e_crs_multiplication/perf_tests/main.cpp
tasks/stl/korotin_e_crs_multiplication/src/ops_stl.cpp

Матрицы хранятся в виде 3х векторов (val, col, row index)
В векторе val хранятся все ненулевые элементы матрицы построчно.
В векторе col того же размера, что и val хранятся номера столбцов, в которых лежат соответствующие элементы из val.
Массив row index представляет собой массив префиксных сумм массива, в котором на i+1 месте лежит количество ненулевых элементов в i-й строке матрицы.
На вход подаются матрицы А и В, хранящиеся в таком виде, для удобного перемножения матриц B транспонируется и умножение происходит в виде "строка на строку", с размещением полученных элементов в матрице-результате.

Коротин Егор. Задача 1. Вариант 4. Технология STL. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – строковый (CRS).

---

tasks/stl/zinoviev_a_convex_hull_components/func_tests/main.cpp
tasks/stl/zinoviev_a_convex_hull_components/include/ops_stl.hpp
tasks/stl/zinoviev_a_convex_hull_components/perf_tests/main.cpp
tasks/stl/zinoviev_a_convex_hull_components/src/ops_stl.cpp

Реализация включает: 
1) Обнаружение связных компонент через поиск в ширину (BFS).
2) Применение алгоритма Эндрю для построения выпуклой оболочки каждой компоненты.
3) Параллелизацию вычислений для независимых компонент с использованием STL (std::thread).
4) Валидацию входных данных (размеры изображения, наличие пикселей).
5) Сохранение результатов в виде массива точек оболочек.

Зиновьев Александр. Вариант 30. Технология STL. Построение выпуклой оболочки для компонент бинарного изображения.

---

tasks/all/kalyakina_a_Shell_with_simple_merge/func_tests/func_all.cpp
tasks/all/kalyakina_a_Shell_with_simple_merge/include/ops_all.hpp
tasks/all/kalyakina_a_Shell_with_simple_merge/perf_tests/perf_all.cpp
tasks/all/kalyakina_a_Shell_with_simple_merge/src/ops_all.cpp

**Принцип работы алгоритма (сортировка по неубыванию):**
1. **Расчет длины подмассивов:** массив разбивается по возможности равномерно на несколько подмассивов для параллельной сортировки по алгоритму Шелла _(распределение по процессам)_.
2. **Выбор интервалов:** выбрана последовательность Седжвика (1, 5, 19, 41, 109, 209, ...). Расчет элементов последовательности происходит до момента, когда следующий элемент последовательности, умноженный на 3, будет больше или равен размеру сортируемого подмассива.
3. **Параллельная сортировка подмассивов:** используется параллельная сортировка Шелла _(распределение по потокам)_. Сортируются элементы, которые находятся на расстоянии текущего интервала друг от друга, после чего происходит уменьшение интервала: выбираем следующий элемент …

Калякина Анастасия. Вариант 15. Технология MPI+TBB. Сортировка Шелла с простым слиянием.

---

tasks/stl/shulpin_i_jarvis_passage/func_tests/main.cpp
tasks/stl/shulpin_i_jarvis_passage/include/ops_stl.hpp
tasks/stl/shulpin_i_jarvis_passage/include/test_modules.hpp
tasks/stl/shulpin_i_jarvis_passage/perf_tests/main.cpp
tasks/stl/shulpin_i_jarvis_passage/src/ops_stl.cpp
tasks/stl/shulpin_i_jarvis_passage/src/test_modules.cpp

Функция MakeJarvisPassageSTL реализует алгоритм Джарвиса для построения выпуклой оболочки из множества точек на плоскости с использованием стандартной библиотеки C++ (STL) и многопоточности. Реализация ориентирована на Linux-платформу (ветка под #ifdef __linux__), где применяются потоки (std::thread), мьютексы (std::mutex) и условные переменные (std::condition_variable) для синхронизации
Принцип работы
- Поиск стартовой точки — самой левой и нижней по координатам.
- Итеративное построение оболочки:
- На каждой итерации запускаются потоки, каждый из которых обрабатывает часть входных данных
- Каждый поток ищет локального кандидата в следующую точку оболочки
- После завершения всех потоков производится глобальный выбор из локальных кандидатов.
-Критерии выбора точки: …

Шульпин Илья. Вариант 23. Технология STL. Построение выпуклой оболочки – проход Джарвиса.

---

tasks/stl/vedernikova_k_gauss/func_tests/main.cpp
tasks/stl/vedernikova_k_gauss/include/ops_stl.hpp
tasks/stl/vedernikova_k_gauss/perf_tests/main.cpp
tasks/stl/vedernikova_k_gauss/src/ops_stl.cpp

Алгоритм:
1. Вычисляется ядро Гаусса размера 3х3 (иначе говоря, распределение), значения элементов зависит от sigma, среднеквадратического отклонения нормального распределения
2. Значения этого распределения используются для построения матрицы свёртки, которая применяется к исходному изображению.
3. Новое значение каждого пикселя устанавливается равным средневзвешенному значению окрестности этого пикселя.

Ведерникова Ксения. Технология STL. Вариант 24. Линейная фильтрация изображений (горизонтальное разбиение). Ядро Гаусса 3x3. 

---

tasks/all/nikolaev_r_hoare_sort_simple_merge/func_tests/func_all.cpp
tasks/all/nikolaev_r_hoare_sort_simple_merge/include/ops_all.hpp
tasks/all/nikolaev_r_hoare_sort_simple_merge/perf_tests/perf_all.cpp
tasks/all/nikolaev_r_hoare_sort_simple_merge/src/ops_all.cpp

Размер входного вектора передаётся от root-процесса остальным с помощью `boost::mpi::broadcast`, затем вектор делится на части, и каждый процесс получает свою часть (`local_vect`). С помощью `boost::mpi::scatterv` выполняется рассеивание данных между процессами (`counts`  — количество элементов, `displs` — смещения элементов). 
Каждый процесс разбивает свой локальный вектор на части (`segments`) для многопоточной сортировки, соответственно, каждая часть сортируется отдельным потоком. Описание использования непосредственно технологии TBB находится в следующем pool request: #165.
С помощью `boost::mpi::gather` организован сбор отсортированных векторов с различных процессов на процессе с рангом 0. Корректное объединение всех отсортированных векторов происходит на root-процессе с …

Николаев Роман. Вариант 13. Технологии MPI+TBB. Сортировка Хоара с простым слиянием.

---

tasks/stl/khasanyanov_k_trapezoid_method/perf_tests/main.cpp
tasks/tbb/khasanyanov_k_trapezoid_method/perf_tests/main.cpp

Fix precision in the perf tests for the identity and correctness of the version comparison

[FIX] Хасаньянов Кирилл. TBB, STL fix 

---

tasks/stl/kovalchuk_a_shell_sort_stl/func_tests/main.cpp
tasks/stl/kovalchuk_a_shell_sort_stl/include/ops_stl.hpp
tasks/stl/kovalchuk_a_shell_sort_stl/perf_tests/main.cpp
tasks/stl/kovalchuk_a_shell_sort_stl/src/ops_stl.cpp

Для каждого значения gap создаём пул потоков (int num_threads = std::min(static_cast<int>(std::thread::hardware_concurrency()), gap);)
Число потоков динамически адаптируется к текущему gap и возможностям процессора.
Распределение работы между потоками через смещение (t) и шаг (num_threads).
Предварительно резервируем память для вектора потоков (reserve).

Ковальчук Александр. Вариант 15. Технология STL. Сортировка Шелла с простым слиянием

---

tasks/all/plekhanov_d_dijkstra/func_tests/main.cpp
tasks/all/plekhanov_d_dijkstra/include/ops_all.hpp
tasks/all/plekhanov_d_dijkstra/perf_tests/main.cpp
tasks/all/plekhanov_d_dijkstra/src/ops_all.cpp

Этот алгоритм находит кратчайшие пути от заданной начальной вершины до всех остальных вершин в графе, используя распределенное параллельное выполнение с помощью Boost.MPI для межпроцессного взаимодействия и OpenMP для внутрипроцессного параллелизма с разделением обрабатываемых вершин между процессами.
* Граф представлен в виде списка смежности (`adj_list`), где для каждой вершины хранится список её соседей и весов рёбер.
* Входные данные графа преобразуются в этот список смежности на каждом MPI процессе.
* Каждый MPI процесс инициализирует локальный вектор расстояний (`local_dist`) до всех вершин как "бесконечность" (`INF`), кроме начальной вершины, расстояние до которой равно 0 (только на процессе с рангом 0).
* Определяется "чанк" вершин (`chunk_size`), который приблизительно равномерно …

Плеханов Даниил. Задача 1. Вариант 21. Технология MPI + OMP. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры).

---

tasks/all/solovyev_d_shell_sort_simple/func_tests/func_all.cpp
tasks/all/solovyev_d_shell_sort_simple/include/ops_all.hpp
tasks/all/solovyev_d_shell_sort_simple/perf_tests/perf_all.cpp
tasks/all/solovyev_d_shell_sort_simple/src/ops_all.cpp

Сортировка Шелла с простым слиянием является модифицированной версией сортировки вставками, где элементы массива сортируются с использованием различных интервалов между элементами.
Начальный интервал, gap - изначально равен длины массива.
Сортируются все подмассивы используя сортировку вставками, индексы подмассивов разделены интервалом gap.
Сначала, данные разделяются между процессами с помощью `boost::mpi::scatterv`
Каждый подмассив в разделенных данных сортируется в своем потоке, создание и разделение подмассивов между потоками происходит при помощи стандартной библиотеки потоков C++ (std::thread).
После этого, интервал уменьшается в два раза и происходит повторная сортировка.
Алгоритм продолжает работу, пока длина интервала не будет равна 1, при длине интервала 1 массив является …

Соловьев Данила. Задача 1. Вариант 15. Технология MPI+STL. Сортировка Шелла с простым слиянием.

---

tasks/omp/bessonov_e_radix_sort_simple_merging/func_tests/main.cpp
tasks/omp/bessonov_e_radix_sort_simple_merging/include/ops_omp.hpp
tasks/omp/bessonov_e_radix_sort_simple_merging/perf_tests/main.cpp
tasks/omp/bessonov_e_radix_sort_simple_merging/src/ops_omp.cpp

1. Параллельное преобразование double в uint64_t:
- #pragma omp parallel for: Каждый поток обрабатывает свою часть массива input_, преобразуя числа в биты с учетом знака.
2. Подсчет частот в каждом проходе:
- #pragma omp parallel: Создаются потоки, каждый из которых считает частоты байтов в своей части данных в local_count.
- #pragma omp for: Распараллеливание цикла по элементам массива bits.
- #pragma omp critical: Суммирование локальных подсчетов в глобальный массив count с синхронизацией.
3. Распределение элементов по потокам:
- #pragma omp parallel: Каждый поток обрабатывает свой сегмент данных:
- Вычисляет текущий байт, сохраняет элементы и их "цифры" в локальные векторы (thread_elements, thread_digits).
- Подсчитывает локальные частоты (thread_counts).
4. Размещение элементов в …

Бессонов Егор. Вариант 19. Технология OMP. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.

---

tasks/all/muhina_m_dijkstra/func_tests/main.cpp
tasks/all/muhina_m_dijkstra/include/ops_all.hpp
tasks/all/muhina_m_dijkstra/perf_tests/main.cpp
tasks/all/muhina_m_dijkstra/src/ops_all.cpp

*    Строится список смежности из входных данных
*    Создается локальная приоритетная очередь (`pq`) для каждого процесса.
*    Инициализируется вектор `local_distances` для каждого процесса. Он хранит текущие оценки кратчайших расстояний от начальной вершины до всех вершин графа. Начальное значение для всех вершин устанавливается в `INT_MAX`.
*   Процесс с рангом 0 устанавливает расстояние до стартовой вершины равным 0.  Затем эта стартовая вершина добавляется в локальную приоритетную очередь `pq` вместе с её расстоянием.
Цикл продолжается до тех пор, пока в системе есть вершины, которые могут улучшить известные расстояния.
*   Каждый процесс пытается извлечь вершину с минимальным расстоянием из своей локальной приоритетной очереди `pq`. Для этого используется функция `try_pop` из TBB
* …

Мухина Маргарита. Вариант 21. Технология MPI+TBB. Поиск кратчайших путей из одной вершины (алгоритм Дейкстры)

---

tasks/all/korotin_e_crs_multiplication/func_tests/main.cpp
tasks/all/korotin_e_crs_multiplication/include/ops_all.hpp
tasks/all/korotin_e_crs_multiplication/perf_tests/main.cpp
tasks/all/korotin_e_crs_multiplication/src/ops_all.cpp

Матрицы хранятся в виде 3х векторов (val, col, row index)
В векторе val хранятся все ненулевые элементы матрицы построчно.
В векторе col того же размера, что и val хранятся номера столбцов, в которых лежат соответствующие элементы из val.
Массив row index представляет собой массив префиксных сумм массива, в котором на i+1 месте лежит количество ненулевых элементов в i-й строке матрицы.
На вход подаются матрицы А и В, хранящиеся в таком виде, для удобного перемножения матриц B транспонируется и умножение происходит в виде "строка на строку", с размещением полученных элементов в матрице-результате.

Коротин Егор. Задача 1. Вариант 4. Технология MPI+STL. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – строковый (CRS).

---

tasks/all/nasedkin_e_strassen_algorithm/func_tests/main.cpp
tasks/all/nasedkin_e_strassen_algorithm/include/ops_all.hpp
tasks/all/nasedkin_e_strassen_algorithm/perf_tests/main.cpp
tasks/all/nasedkin_e_strassen_algorithm/src/ops_all.cpp

Реализация алгоритма Штрассена. Технология MPI+STL.

Наседкин Егор. Задача 1. Вариант 3. Технология MPI+STL. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

---

tasks/all/odintsov_m_multmatrix_cannon/func_tests/func_all.cpp
tasks/all/odintsov_m_multmatrix_cannon/include/ops_all.hpp
tasks/all/odintsov_m_multmatrix_cannon/perf_tests/main.cpp
tasks/all/odintsov_m_multmatrix_cannon/src/ops_all.cpp

Структура программы
Программа разделена на две части: межпроцессное распределение (MPI - RunImpl) и внутрипроцессное параллельное вычисление (STL - ProcessBlock).
MPI: Распараллеливание по блокам
На первом этапе пространство задач разбивается на квадратную сетку процессов, в которой каждый процесс отвечает за вычисление одной подматрицы (или блока) результирующей матрицы. В частности:
Матрицы A и B разбиваются на блочную структуру одинакового размера.
Каждому MPI-процессу назначается координата в сетке и соответствующие блоки A и B.
Процессы выполняют начальную сдвижку блоков по алгоритму Кэннона: блоки матриц A и B смещаются так, чтобы минимизировать последующие пересылки.
В ходе основного вычисления:
Каждый процесс выполняет несколько шагов, в каждом из которых перемножает текущие …

Одинцов Михаил. Задача 1. Вариант 1. Технология STL+MPI. Умножение плотных матриц,типа double,блочная схема, алгоритм Кэннона

---

tasks/all/ermolaev_v_graham_scan/func_tests/main.cpp
tasks/all/ermolaev_v_graham_scan/include/ops_all.hpp
tasks/all/ermolaev_v_graham_scan/perf_tests/main.cpp
tasks/all/ermolaev_v_graham_scan/src/ops_all.cpp

Части программы подвергшиеся параллелизму:
- Параллельная сортировка (ParallelSort, MPI+OMP) 
- Поиск минимального элемента (IndexOfMinElement)
- Проверка коллинеарности точек (IsAllCollinear)
- Проверка идентичности точек (IsAllSame)
Сам алгоритм Грэхема выполняется последовательно, так как он имеет существенные зависимости между итерациями. Распараллеливание сосредоточено на подготовительных шагах, где параллелизм наиболее эффективен.

Ермолаев Владислав. Задача 1. Вариант 22. Технология MPI+OMP. Построение выпуклой оболочки – проход Грэхема.

---

tasks/all/konkov_i_sparse_matmul_ccs_all/func_tests/func_all.cpp
tasks/all/konkov_i_sparse_matmul_ccs_all/include/ops_all.hpp
tasks/all/konkov_i_sparse_matmul_ccs_all/perf_tests/perf_all.cpp
tasks/all/konkov_i_sparse_matmul_ccs_all/src/ops_all.cpp

Код реализует параллельное умножение разреженных матриц в формате CCS (Compressed Column Storage) с использованием MPI для распределения вычислений между процессами и многопоточности для оптимизации внутри узла. Алгоритм разделяет столбцы матрицы B между процессами, обрабатывает их параллельно с помощью потоков, а затем собирает результаты на главном процессе. Проект включает функциональные тесты (проверка корректности умножения, обработка граничных случаев) и производительностные тесты (замер времени выполнения для матриц 5000×5000). Для обеспечения сериализации данных в MPI используются модификации Boost, а валидация результатов выполняется через Google Test.

Коньков Иван. Задача 4. Вариант 5 Технология MPI+STL. Умножение разреженных матриц. Элементы типа double. Формат хранения матрицы – столбцовый (CCS).

---

tasks/all/kolodkin_g_multiplication_matrix_CRS/func_tests/func_all.cpp
tasks/all/kolodkin_g_multiplication_matrix_CRS/include/ops_all.hpp
tasks/all/kolodkin_g_multiplication_matrix_CRS/perf_tests/perf_all.cpp
tasks/all/kolodkin_g_multiplication_matrix_CRS/src/ops_all.cpp

Описание параллельной задачи:
На вход подается вектор, который содержит данные двух разреженных матриц.
Preproccessing: на этом этапе считывается входной вектор, разделяется на две части(каждый подвектор соответствует данным одной из двух матриц), после чего каждый вектор с помощью функции парсится в структуру SparseMatrixCRS. На выходе получаются две объекта типа SparseMatrixCRS, которые представляют матрицы, которые требуется перемножить.
Validation: проверяется, что количество столбцов первой матрицы равно количеству строк второй матрицы. Если это условие не выполнено, то умножение невозможно.
Run: параллелизм осуществляется за счет распараллеливания цикла с помощью процессов. Определяется количество процессов и создается вектор формата координата-значение для хранения локальных …

Колодкин Григорий. Вариант 6. MPI+STL. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – строковый (CRS).

---

tasks/omp/vedernikova_k_gauss/perf_tests/main.cpp
tasks/seq/vedernikova_k_gauss/perf_tests/main.cpp
tasks/tbb/vedernikova_k_gauss/perf_tests/main.cpp
tasks/tbb/vedernikova_k_gauss/src/ops_tbb.cpp

Изменила размеры в perf_tests, чтобы они совпадали c STL и MPI+STL версиями

[FIX] Ведерникова Ксения. Технологии SEQ, OMP, TBB. Вариант 24. Линейная фильтрация изображений (горизонтальное разбиение). Ядро Гаусса 3x3.

---

tasks/stl/prokhorov_n_multidimensional_integrals_by_trapezoidal_method/func_tests/main.cpp
tasks/stl/prokhorov_n_multidimensional_integrals_by_trapezoidal_method/include/ops_stl.hpp
tasks/stl/prokhorov_n_multidimensional_integrals_by_trapezoidal_method/perf_tests/main.cpp
tasks/stl/prokhorov_n_multidimensional_integrals_by_trapezoidal_method/src/ops_stl.cpp

Эта версия реализует **многомерное интегрирование методом трапеций** с использованием параллельной обработки на базе `std::thread` из стандартной библиотеки C++ (STL Threads).
---
- Использование `std::thread` для создания рабочих потоков
- Ручное распределение работы между потоками (**chunk-based** подход)
- Локальные копии данных для каждого потока
- Явная синхронизация выполнения через `join()`
---
- Ограничение максимального количества потоков (обычно **до 4–8**)
- Использование **локальных переменных** в потоках для минимизации конфликтов
- Оптимальное распределение диапазонов интегрирования
- **Автоматическое переключение** на последовательный режим при малом объеме вычислений
---
- Наибольший прирост производительности для **2D–4D** задач  
*(5–6x ускорение на 6-ядерном CPU)*
- …

Прохоров Никита. Вариант 10. Технология STL. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).

---

tasks/all/zolotareva_a_SLE_gradient_method/func_tests/main.cpp
tasks/all/zolotareva_a_SLE_gradient_method/include/ops_seq.hpp
tasks/all/zolotareva_a_SLE_gradient_method/perf_tests/main.cpp
tasks/all/zolotareva_a_SLE_gradient_method/src/ops_seq.cpp

В данном проекте реализован метод сопряжённых градиентов (CG) для решения системы линейных алгебраических уравнений вида $A x = b,$ где:
* $A$ — симметричная положительно определённая матрица размера $n\times n$.
* $b$ — вектор правой части длины $n$.
* $x$ — искомое решение.
* **MPI** — распределяет матрицу и вектор между процессами по строкам.
* **OpenMP** — распараллеливает вычислительно тяжёлые локальные операции внутри каждого MPI-процесса.
```cpp
// На процессе 0 разбиваем строки матрицы A и вектора b
int base_rows = n_ / world_size;
int remainder = n_ % world_size;
local_rows = base_rows + (rank == 0 ? remainder : 0);
if (rank == 0) {
int start = local_rows;
for (int p = 1; p < world_size; ++p) {
world.send(p, 0, a_.data() + start * n_, base_rows * n_);
world.send(p, 1, b_.data() + …
```

Золотарева Арина. Вариант 8. Технология MPI+OMP. Решение систем линейных уравнений методом сопряженных градиентов.

---

tasks/tbb/bessonov_e_radix_sort_simple_merging/func_tests/main.cpp
tasks/tbb/bessonov_e_radix_sort_simple_merging/include/ops_tbb.hpp
tasks/tbb/bessonov_e_radix_sort_simple_merging/perf_tests/main.cpp
tasks/tbb/bessonov_e_radix_sort_simple_merging/src/ops_tbb.cpp

**Реализация алгоритма**
1. Преобразование double → uint64_t:
Для обеспечения корректного порядка сортировки чисел (double), каждое число конвертируется в 64-битное целое значение специальным образом:
- Положительные числа: инвертирование только знакового бита.
- Отрицательные числа: побитовая инверсия всех битов.
2. Поразрядная сортировка (Radix Sort):
Реализована поразрядная сортировка на 8 проходов по 8 бит (64 бита в сумме).
Сортировка внутри каждого чанка производится параллельно через tbb::parallel_for.
3. Параллельная обработка чанков:
Входной массив делится на равные части (чанки) по количеству потоков.
Каждый чанк сортируется независимо в отдельном потоке.
4. Параллельное слияние отсортированных чанков:
Сортированные чанки объединяются с помощью итеративного попарного слияния …

Бессонов Егор. Вариант 19. Технология TBB. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.

---

tasks/stl/mezhuev_m_bitwise_integer_sort_with_simple_merge/func_tests/main.cpp
tasks/stl/mezhuev_m_bitwise_integer_sort_with_simple_merge/include/ops_stl.hpp
tasks/stl/mezhuev_m_bitwise_integer_sort_with_simple_merge/perf_tests/main.cpp
tasks/stl/mezhuev_m_bitwise_integer_sort_with_simple_merge/src/ops_stl.cpp

Задача реализует поразрядную сортировку целых чисел с простым слиянием. Вначале происходит предобработка данных, где входной массив чисел делится на положительные и отрицательные. Для каждого массива запускаются отдельные потоки, выполняющие поразрядную сортировку чисел. После сортировки отрицательные числа переворачиваются, и оба массива сливаются: сначала идут отрицательные, затем положительные числа. В конце отсортированные данные копируются в выходной массив. Используется многопоточность для ускорения сортировки и обработки чисел с разными знаками.

Межуев Максим. Вариант 17. Технология STL.  	 Поразрядная сортировка для целых чисел с простым слиянием.

---

tasks/seq/fomin_v_conjugate_gradient/func_tests/main.cpp
tasks/seq/fomin_v_conjugate_gradient/include/ops_seq.hpp
tasks/seq/fomin_v_conjugate_gradient/perf_tests/main.cpp
tasks/seq/fomin_v_conjugate_gradient/src/ops_seq.cpp
tasks/seq/poroshin_v_multi_integral_with_trapez_method/perf_tests/main.cpp

Этот код реализует последовательную версию метода сопряжённых градиентов для решения систем линейных уравнений вида Ax = b, где A — квадратная матрица, а b — вектор. 
Основные этапы:
1. Preprocessing:
Из входных данных извлекается матрица A (размером n×n) и вектор b (длины n)
Определяется размерность системы n по формуле из длины входного массива
2. Валидация:
Проверяет корректность размера входных данных
Убеждается, что выходной буфер имеет правильный размер
3. Выполнение алгоритма:
Инициализирует начальное приближение x = 0
Вычисляет начальную невязку r = b - Ax (в данном случае r = b)
Итеративно обновляет решение, используя ортогональные направления поиска
Останавливается при достижении точности (||r|| < ε) или максимального числа итераций
Вспомогательные функции:
Скалярное …

Фомин Владимир. Вариант 8. Технология SEQ. Решение систем линейных уравнений методом сопряженных градиентов

---

tasks/omp/frolova_e_Sobel_filter/include/ops_omp.hpp
tasks/omp/frolova_e_Sobel_filter/src/ops_omp.cpp
tasks/tbb/frolova_e_Sobel_filter/include/ops_tbb.hpp
tasks/tbb/frolova_e_Sobel_filter/src/ops_tbb.cpp

removed the function convert to gray world in pre-processing to speed up the program

[FIX PERFOMANCE]Фролова Елизавета. Вариант 27. Технология OMP. Выделение ребер на изображении с использованием оператора Собеля.
